### ISSUE TITLE
Sender ID aka. SPFv2 support? 

### ISSUE THREAD

**Issue by Avamander** [foxcpp/maddy#100]
Given that maddy is MIT there should be nothing really stopping it from implementing Sender ID, would it maybe be worth supporting?

**Comment by emersion** [comment]
Duplicate of https://github.com/emersion/maddy/issues/91

**Comment by Avamander** [comment]
SPFv2 is a bit different than SPFv1 though, it's a tad different and has a different spec.

**Comment by emersion** [comment]
Eh, I don't know about SPFv2. Link?

**Comment by emersion** [comment]
Bleh. Doesn't seem very different from SPF to me.

**Comment by Avamander** [comment]
https://en.wikipedia.org/wiki/Sender_ID
https://tools.ietf.org/html/rfc4406

**Comment by foxcpp** [comment]
Speaking of header fields verification, this is defined by DMRAC too and it is more widely deployed. So I might say we don't need SPFv2 that much, do we?

**Comment by foxcpp** [comment]
Is SPFv2 wide-spread? I don't think so, also as I said, DMRAC can supersede it. The linked RFC is only "EXPERIMENTAL" and never got anywhere. I can't see a reason to support SPFv2, is there any?

**Comment by Avamander** [comment]
I guess not.
