### ISSUE TITLE
maddy sometimes fails to do anything

### ISSUE THREAD

**Issue by chaoticryptidz** [foxcpp/maddy#105]
[root@kittehserv maddy]# ./maddy -config maddy.conf 
^C
[root@kittehserv maddy]# ./maddy -config maddy.conf 
16.07.19 11:07:09 smtp: listening on smtp://0.0.0.0
^C
[root@kittehserv maddy]# ./maddy -config maddy.conf 
16.07.19 11:07:11 imap: listening on imaps://0.0.0.0
16.07.19 11:07:11 imap: listening on imap://0.0.0.0
16.07.19 11:07:11 smtp: listening on smtp://0.0.0.0

each ^C was about 5s apart, no matter how long you leave it it only somtimes works and listens on all

**Comment by foxcpp** [comment]
The debug log would be helpful. Side note: add an issue template that says it. TODO.

**Comment by foxcpp** [comment]
Can't reproduce with the default configuration. Output after Ctrl+\ (SIGTRAP) would be helpful.

**Comment by foxcpp** [comment]
Here are my steps:
1. `git clone github.com/emersion/maddy` and `go build` maddy binary
2. Copy default config into the binary directory, change tls to self_signed, change ports so it can bind without root.
3. Tried to start it like 20 times, all times it was starting properly and working.
