### ISSUE TITLE
Out of memory crash after being fed by zeros

### ISSUE THREAD

**Issue by foxpy** [foxcpp/maddy#116]
Steps to reproduce:
1) run maddy as usual;
2) `netcat example.com 25 </dev/zero`.

Result:
`fatal error: runtime: out of memory`
Expected result:
`500 5.5.2 Too many unrecognized commands` in answer to netcat instance, closing TCP connection.

**Comment by foxcpp** [comment]
Adding "security" label, this can be used to bring servers down.

**Comment by foxcpp** [comment]
Notes:
- Turning io_debug fixes this issue (server keeps ignoring invalid output instead of killing connection, though)
- IMAP endpoint is not affected
- Using ~~delicious~~ /dev/urandom instead of /dev/zero results in expected behavior

@emersion, do you have any ideas what might cause this?

**Comment by foxcpp** [comment]
Okay, net/textproto.Reader.ReadLine simply keeps buffering a line with infinite length.
We need some reasonable restriction here.

**Comment by foxpy** [comment]
> net/textproto.Reader.ReadLine simply keeps buffering a line with infinite length

Can we have some replacement for net/textproto.Reader.ReadLine?

**Comment by foxcpp** [comment]
>Can we have some replacement for net/textproto.Reader.ReadLine?

Apparently, we would have to replace almost all Reader functions. ~~The best way, I think is to copy-paste Reader implementation into go-smtp and fix it there. But this is a temporary solution, of course.~~ See next post.

**Comment by foxcpp** [comment]
According to the documentation, this is by design, though and users should wrap the underlying Reader.
