### ISSUE TITLE
Null (empty) MAIL FROM address should be accepted as valid

### ISSUE THREAD

**Issue by foxcpp** [foxcpp/maddy#131]
It is a special-case value that is used for certain types of automated replies (e.g. DSNs, MDNs).

See https://tools.ietf.org/html/rfc5321#section-4.5.5.

**Comment by foxcpp** [comment]
CC @emersion

**Comment by emersion** [comment]
https://github.com/emersion/go-smtp/pull/57

**Comment by foxcpp** [comment]
Ah, missed that.
