### ISSUE TITLE
Evaluate compatibility with MLM software

### ISSUE THREAD

**Issue by foxcpp** [foxcpp/maddy#157]
Somebody needs to document what popular MLM (mailing list management) software expect from MTA and we can/should do to fit these expectations.

- maddy uses "non-traditional" storage format (not maildir). This might cause problems if MLM software wants to read mail directly from disk. We can implement delivery-only support for maildir/mbox, though.

- maddy currently lacks any support for "delivery to system command" and LMTP forwarding. Both might be used by MLM to accept messages as an alternative to the first approach.

- VERP is needed for efficient bounce handling. This relies on suffix dropping in MTA which is supported by maddy (replace_rcpt module).

- ???

**Comment by prologic** [comment]
Not having had much experience with mailing list software for quite some time now (I really don't like mailing lists anyway); can we exteralize this problem such that it has no direct impact on the design/implementation of maddy itself?

**Comment by foxcpp** [comment]
@prologic That's what the second point in initial post is about. We implement common ways for integration with external software and expect MLM to do the same.

From what I see in the documentation, [Mailman 3](http://docs.mailman3.org/en/latest/config-core.html#configuring-mta) uses LMTP to accept messages. [Sympa](https://sympa-community.github.io/manual/install/configure-mail-server.html) wants MTA to call an external executable for delivery. Both can be supported by maddy without significant problems. What Mailman 2 needs is a mystery, though... But I don't think we really want to support it.

Additionally, Sympa needs a sendmail-compatible command, this can be provided by external software such as msmtp.

**Comment by prologic** [comment]
Can't we just provide "compatibility binaries" for interop?

**Comment by foxcpp** [comment]
Not sure what do you mean by "compatibility binaries" here. If you are referring to sendmail - it makes no sense, since at this point such binary will do exactly what any "nullmailer" (like msmtp) does.

**Comment by Avamander** [comment]
It might be nice to create a section in the documentation about MLM software and mention there that any nullmailer (e.g. `msmtp`) does what `sendmail` would do. That way people can more easily get started with using maddy with MLM software.

**Comment by foxcpp** [comment]
06d228cfe22583c1f0177d4a6bd388805dc58cf3 adds documentation page explaining how to configure Mailman 3 for maddy.
