### ISSUE TITLE
Reload certificates on change

### ISSUE THREAD

**Issue by svanichkin** [foxcpp/maddy#160]
# Use case

Now specifying the path to the certificates, they are cached. If the certificate is expired, or the certificates themselves are updated on the specified paths to the fresh ones, they server will still use the old ones.

In order for the server to accept fresh certificates, you need to monitor so that the certificates do not expire, then specify the fresh certificates and restart the server. It is not acceptable.

# Your idea for a solution

It would be great if the server periodically (once a day) would take certificates (since they might have already been updated).

Thanks.

**Comment by foxcpp** [comment]
Reloading once a day may not be enough, depending on the cert expiration time. There filesystem needs to be polled rather often or watched using something like inotify (not portable).

 I don't think this is important, though. If you have external software managing certificates, look for the post-update hook functionality in it and configure it to restart maddy. Exact instructions for certbot are on [the wiki](https://github.com/foxcpp/maddy/wiki/Tutorial:-Setting-up-a-mail-server-with-maddy#lets-encrypt-and-certbot).

**Comment by svanichkin** [comment]
This is an important thing, as the server after seeing the certificate elapsed by the time of completion must somehow act. This may be a mistake, or it may be a verification of certificates (maybe they are new).
Or, it may be possible to integrate obtaining certificates for let’s encrypt directly into the server (without using third-party scripts), as is done in caddy.

**Comment by ascent12** [comment]
>Or, it may be possible to integrate obtaining certificates for let’s encrypt directly into the server

The current [challenge types](https://letsencrypt.org/docs/challenge-types/) require it to either be an HTTPS or DNS server, which seems out-of-scope here.

**Comment by foxcpp** [comment]
Discussion of let's encrypt integration is in #3. So far the consensus is that maddy should not do it.

**Comment by svanichkin** [comment]
At least just checking that the certificate has expired. Then try to take the certificates again along the same paths (maybe they are updated). Making third-party scripts to restart maddy is not entirely good.
