### ISSUE TITLE
DKIM signing generates broken signatures due to header folding

### ISSUE THREAD

**Issue by foxcpp** [foxcpp/maddy#187]
Got my hands to actually test it. Basically, go-msgauth/dkim generates a DKIM-Signature field value and signs it. Then modify/dkim code inserts that value into the textproto.Header. textproto (re)folds it and then also modifies field name from DKIM-Signaure to Dkim-Signature.

This breaks the signature as the header value is different, here is the example of modifications:

sigField as signed: 
```
DKIM-Signature: a=rsa-sha256; bh=uI/rVH7mLBSWkJVvQYKz3TbpdI2BLZWTIMKcuo0KHO
 I=; c=simple/simple; d=example.org; h=Subject:To:From; s=default; t=1577562
 184; v=1; b=;
```
sigField as written (and thus verified): 
```
Dkim-Signature: a=rsa-sha256;
 bh=uI/rVH7mLBSWkJVvQYKz3TbpdI2BLZWTIMKcuo0KHOI=; c=simple/simple;
 d=example.org; h=Subject:To:From; s=default; t=1577562184; v=1;
 b=;
```

CC @emersion 
I believe we discussed the usefulness of "AddRaw" for textproto.Header to bypass the folding algorithm. But not sure what to do with the field name, though.

<details>

<summary>Self-contained test case</summary>

```go
package main

import (
	"bytes"
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"encoding/base64"
	"fmt"
	"io"
	"net"

	"github.com/emersion/go-message/textproto"
	"github.com/emersion/go-msgauth/dkim"
	"github.com/foxcpp/go-mockdns"
)

func main() {
	hdr := textproto.Header{}
	hdr.Add("From", "<a@example.org")
	hdr.Add("To", "<b@example.org")
	hdr.Add("Subject", "Hi")
	body := "Hai there!\r\n"

	// Create new key for signing.

	pkey, err := rsa.GenerateKey(rand.Reader, 1024)
	if err != nil {
		fmt.Println(err)
		return
	}

	// Prepare the DNS record for key.

	keyBlob, err := x509.MarshalPKIXPublicKey(pkey.Public())
	if err != nil {
		fmt.Println(err)
		return
	}

	// That's why we need VerifierOptions or something!
	srv, err := mockdns.NewServer(map[string]mockdns.Zone{
		"default._domainkey.example.org.": {
			TXT: []string{"v=DKIM1; k=rsa; p=" + base64.StdEncoding.EncodeToString(keyBlob)},
		},
	})
	if err != nil {
		fmt.Println(err)
		return
	}
	defer srv.Close()
	srv.PatchNet(net.DefaultResolver)

	// Sign.

	opts := dkim.SignOptions{
		Domain:   "example.org",
		Selector: "default",
		Signer:   pkey,
	}

	s, err := dkim.NewSigner(&opts)
	if err != nil {
		fmt.Println(err)
		return
	}
	textproto.WriteHeader(s, hdr)
	io.WriteString(s, body)
	if err := s.Close(); err != nil {
		fmt.Println(err)
		return
	}
	hdr.Add("DKIM-Signature", s.SignatureValue())

	// Verify.

	var b bytes.Buffer
	textproto.WriteHeader(&b, hdr)
	b.WriteString(body)

	vs, err := dkim.Verify(bytes.NewReader(b.Bytes()))
	if err != nil {
		fmt.Println("DKIM FAIL", err)
		return
	}

	for _, v := range vs {
		if v.Err != nil {
			fmt.Println("DKIM verification fail:", v.Err)
		}
	}
}
```

</details>

**Comment by emersion** [comment]
Hmm, that's one of the reasons why I didn't want to expose too many internals to library users.

I think we should only expose the whole header from `dkim` (raw key + value).

**Comment by foxcpp** [comment]
Ugh, this is going to give me a lot of headaches since I already built maddy with the idea that textproto.Header is suitable as a generic header container and builder.

I guess I will have to replace or at least wrap it to handle additions differently.

**Comment by emersion** [comment]
I'm not against adding a function to merge two `textproto.Header` or to add a raw (key + value) field to an existing `textproto.Header`.

**Comment by foxcpp** [comment]
>or to add a raw (key + value) field to an existing textproto.Header.

I will take a look at it.

Wrapping or replacing textproto will result in lots of duplicated effort and I would like to avoid that.

**Comment by emersion** [comment]
>Wrapping or replacing textproto will result in lots of duplicated effort and I would like to avoid that.

Yeah, I agree this would be very annoying.
