### ISSUE TITLE
Consistency problems in go-imap-sql DB

### ISSUE THREAD

**Issue by foxcpp** [foxcpp/maddy#190]
# Describe the bug

1. Message counters can go negative causing STATUS to fail.
2. Messages can be removed from the disk without actually being removed from index.

# Steps to reproduce

1. Add the message to DB (using SMTP delivery interface?)
2. Remove it.
3. !?

# Log files

<details>
<summary>Some bits related to problem</summary>

```
maddy[31238]: sql: Status (messages count) [[MESSAGES RECENT UNSEEN UIDNEXT UIDVALIDITY]]: sql: Scan error on column index 0, name "msgsCount": converting driver.Value type int64 ("-1") to a uint32: invalid syntax         {"mbox":"Sent","mboxId":9,"username":"[REDACTED]@foxcpp.dev","uid":2}
maddy[31238]: sql: Status (messages count) [[MESSAGES RECENT UNSEEN UIDNEXT UIDVALIDITY]]: sql: Scan error on column index 0, name "msgsCount": converting driver.Value type int64 ("-1") to a uint32: invalid syntax         {"mbox":"Junk","mboxId":7,"username":"[REDACTED]@foxcpp.dev","uid":2}
maddy[31238]: sql: ListMessages (scan) [true 1:3 [UID RFC822.SIZE FLAGS BODY.PEEK[HEADER.FIELDS (FROM TO CC BCC SUBJECT DATE MESSAGE-ID PRIORITY X-PRIORITY REFERENCES NEWSGROUPS IN-REPLY-TO CONTENT-TYPE REPLY-TO)]]]: openBody: open messages/dae875319dff62504e316f0d356519ec: no such file or directory         {"mbox":"Trash","mboxId":8,"username":"[REDACTED]@foxcpp.dev","uid":2}
```

</details>

# Configuration file

Default configuration.

# Environment information

```
maddy v0.0.0-20200102161210-813bbb992e74 h1:vwhd+fpNQCDYlod58o5ThzjDPUNaNs/unEpMrQNSSC0=
```

**Comment by foxcpp** [comment]
The problem is in MOVE command implementation. It needs rewrite anyway, but the current implementation causes msgsCount to go negative because it decrements it by 2*N for N moved messages.

**Comment by MFAshby** [comment]
I hit this, and it caused an error since the code tries to parse the value as an unsigned. This broke stuff for my inbox on some MUAs (alps webmail and evolution)
```
Sep 25 21:29:33 somehost maddy[269435]: imapsql: Status: messages scan []: sql: Scan error on column index 0, name "msgscount": converting driver.Value type int64 ("-15909") to a uint32: invalid syntax         {"username":"<<<REMOVED>>>","uid":1}
```

I'm not sure how it got to be negative. Is this column an optmization? It looks like it should match the number of messages in msgs table. Possible improvements; 
1. set a check constraint on the database to fail if the msgscount is tried to set below zero
2. periodically(?) check msgscount against the actual count of messages in msgs table and adjust in case it got out of sync (though this just hides the bug I guess)

**Comment by MFAshby** [comment]
Using evolution mail, deleting the only mail in my inbox seems to result in this behaviour quite reliably.
```
$ maddy version
0.6.2 linux/arm64 go1.18.3

default config: /etc/maddy/maddy.conf
default state_dir: /var/lib/maddy
default runtime_dir: /run/maddy
```

**Comment by MFAshby** [comment]
Enabled debug logging with `debug yes` directive. I'm running backed by postgresql.

[maddy.log](https://github.com/foxcpp/maddy/files/9641795/maddy.log)

**Comment by MFAshby** [comment]
Maybe I have some kind of data consistency problem; there are many rows in the `flags` table without a corresponding row in the `msgs` table: 
```
maddy=> select count(*) from flags left outer join msgs on flags.msgid = msgs.msgid where msgs.msgid is null;
 count
-------
   319
(1 row)
```

edit: I definitely have a consistency problem, but based on the implementation in go-imap-sql, I am somehow missing a foreign key constraint and a cascade on the `flags` table:

https://github.com/foxcpp/go-imap-sql/blob/df3b66a5b04f4036237d7b150c134b5279be8835/sql.go#L171

I have deleted the invalid flags data, and added the constraint, and also added the below double check in case any bug ever really happened which caused msgscount to become invalid:
```
maddy=> alter table mboxes add constraint mboxes_msgscount_check check (msgscount >= 0);
ALTER TABLE
```

Sorry for the noise!
