### ISSUE TITLE
 https://foxcpp.dev/maddy/ - is not available

### ISSUE THREAD

**Issue by v1a0** [foxcpp/maddy#193]
https://foxcpp.dev/maddy/ - is not available

**Comment by foxcpp** [comment]
Sorry, I screwed some stuff up and it is currently offline. If you are looking for build.sh, it can be found in the repo root. All documentation is in the [docs/](https://github.com/foxcpp/maddy/tree/master/docs) directory

**Comment by foxcpp** [comment]
Fixed.
