### ISSUE TITLE
libc-dev required on debian to build maddy

### ISSUE THREAD

**Issue by bn4t** [foxcpp/maddy#216]
# Describe the bug

I noticed that building maddy with the build script fails on debian 10 if the g++ package isn't installed

# Steps to reproduce

1. Fresh VM with debian 10
2. `apt-get install gcc git curl`
3. `curl 'https://foxcpp.dev/maddy/build.sh' | bash`
This produces following error:
````
[...]
go: finding github.com/go-sql-driver/mysql v1.5.0
go: finding github.com/pierrec/lz4 v2.4.1+incompatible
# runtime/cgo
_cgo_export.c:3:10: fatal error: stdlib.h: No such file or directory
 #include <stdlib.h>
          ^~~~~~~~~~
compilation terminated.
````

Installing the `g++` package fixes this.

# Log files
[Full log](https://paste.sr.ht/%7Ebn4t/9967c914e41015bb0920e3a8ab7688c9fbcad6d5)

# Environment information
uname -a: `Linux mail 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux`

**Comment by ascent12** [comment]
It'll be the `libc6-dev` package that provided that, rather than g++ directly.

**Comment by foxcpp** [comment]
According to this page: https://packages.debian.org/buster/gcc
Installing `gcc` pulls libc development files as a dependency. 

The maddy documentation here: https://foxcpp.dev/maddy/tutorials/setting-up/#installing-maddy
Says you need a C compiler and provides the example command for Debian-based distros:
```
# apt-get install gcc git curl
```

What is wrong?

**Comment by foxcpp** [comment]
Ah, I see, it is "recommends", not requires. I should update the referenced page to mention "C toolchain" instead of just "C compiler" and include libc6-dev in the command.
