### ISSUE TITLE
Reduce maddyctl executable size

### ISSUE THREAD

**Issue by foxcpp** [foxcpp/maddy#220]
See if it is possible to not add all server code into it.

**Comment by foxcpp** [comment]
Not registering all modules cuts only 3 MiB (23 MiB -> 20 MiB with non-PIE build for linux/amd64).
Ultimate solution would be to squash maddyctl functionality into main server executable.

**Comment by foxcpp** [comment]
maddyctl, maddy executables together are 52 MiB. Arch packages for Postfix, Dovecot, OpenDKIM and OpenDMARC together are 18.25 MiB. Should we care?

**Comment by jcmdln** [comment]
A few extra MiB might be shaved by building with `-ldflags='-w -s'`, though I don't think this alone makes a sufficient case for worry.

```
$ go build && du -h maddy
22M    maddy
$ go build -ldflags='-w -s' && du -h maddy
16M    maddy
```
```
$ go build && du -h maddyctl
23M     maddyctl
$ go build -ldflags='-w -s' && du -h maddyctl
16M    maddyctl
```

It may be reasonable to explore combining several approaches to see if the savings can be non-trivial, though the total used space by the full bundle of executables currently appear to be quite reasonable.  Other potential options would include using `upx` for compressing the resulting binaries, but maybe this isn't the correct approach to include early into this discussion until after other options have been explored and/or utilized.

**Comment by foxpy** [comment]
> Other potential options would include using `upx` for compressing the resulting binaries, but maybe this isn't the correct approach to include early into this discussion until after other options have been explored and/or utilized.

@jcmdln I believe shaving off debug info or even compressing with UPX is not a developers' approach to reduce executable size, but rather a distribution maintainers' choice. The main issue here is amount of code included in maddyctl. Standard issue hello-world compiled with a standard issue go compiler is size of "just" 2 MiB compared to 23 MiB behemoth we have.


> maddyctl, maddy executables together are 52 MiB. Arch packages for Postfix, Dovecot, OpenDKIM and OpenDMARC together are 18.25 MiB. Should we care?

@foxcpp Possibly there is nothing to care about. 50 MiB would cause virtually no issues even on cheapest servers one can afford.

**Comment by jcmdln** [comment]
@foxpy To clarify the context around the project when my comments were made:

* My thoughts were shared one day before [v0.3.0]( https://github.com/foxcpp/maddy/releases/tag/v0.3.0) was released, which was the first release that didn't include binaries
* The `build.sh` included with this project was not marked for eventual deprecation, which as of the time of writing [still modifies](https://github.com/foxcpp/maddy/blob/master/build.sh#L124) `LDFLAGS` and is used by the [Dockerfile](https://github.com/foxcpp/maddy/blob/master/Dockerfile) to create the official container

I feel that in this context my observations were quite reasonable.

**Comment by foxcpp** [comment]
@jcmdln FYI 0.3.0 was an unfortunate outlier, newer releases also include binary artifacts. Though I had to give up on perfect reproductive builds.

**Comment by foxcpp** [comment]
And yeah, way to go would be to put maddyctl into the same executable. Making it `maddy serve` and the rest of commands from maddyctl. That would need some work to either move everything to or from urfave/cli library that is currently used by maddyctl.

**Comment by foxcpp** [comment]
Superseded by #432.
