### ISSUE TITLE
Outbound rate limit is applied to the sender instead of the recipient

### ISSUE THREAD

**Issue by wjywbs** [foxcpp/maddy#234]
# Use case

What problem you are trying to solve?

limits outbound_limits {
    # Up to 20 msgs/sec across max. 10 SMTP connections
    # for each recipient domain.
    destination rate 20 1s
    destination concurrency 10
}

The rate limit domain is the sender's domain $(local_domains) instead of the recipient's domain such as gmail.com or yahoo.com.
https://github.com/foxcpp/maddy/blob/master/internal/target/remote/remote.go#L215

Note alternatives you considered and why they are not useful.

# Your idea for a solution

How your solution would work in general?
Note that some overly complicated solutions may be rejected because maddy is
meant to be simple.

Apply rate limit on the the recipient's domain. Maybe keep "source rate 20 1s" to limit the sender.

- [ ] I'm willing to help with the implementation

**Comment by foxcpp** [comment]
Are you able to confirm the issue?

Per-recipient domain rate-limiting is applied here: https://github.com/foxcpp/maddy/blob/ab948e149444536d5fd45d7b504ca266ecff0870/internal/target/remote/connect.go#L178

TakeMsg function call you referenced is responsible for per-message rate-limiting including one based on source domain as can be seen here:
https://github.com/foxcpp/maddy/blob/ab948e149444536d5fd45d7b504ca266ecff0870/internal/limits/limits.go#L167

**Comment by wjywbs** [comment]
I think you are right. The "source" option in limits is not mentioned in the docs.

**Comment by foxcpp** [comment]
Documentation corrected in e9a418093135dfa2576060ce7c311ac055c4e932.
