### ISSUE TITLE
Outbound connection reuse

### ISSUE THREAD

**Issue by wjywbs** [foxcpp/maddy#235]
# Use case

What problem you are trying to solve?
Currently the connection is only reused if there are multiple recipients of the same domain in an email. Each email creates a new connection with TLS to the recipient server.

Note alternatives you considered and why they are not useful.
The connection overhead is large when the number of outbound emails is large.

# Your idea for a solution

How your solution would work in general?
Note that some overly complicated solutions may be rejected because maddy is
meant to be simple.

Move per email connection reuse to global connection reuse. Set a limit on the number of times that the connection can be reused.

- [ ] I'm willing to help with the implementation

**Comment by foxcpp** [comment]
This is a fair idea. Do other servers have limitation on number of messages per connection hence the limit is needed here?

Some considerations I can think of:

1. It is important to check for connection usability as deployed servers have different timeout configurations including some violating RFC 5321 recommendations. NOOP command can be used for that and we can likely discard connections idling for more than 5 minutes without that.
2. It is important to properly carry over security policy state and possibly avoid DANE/MTA-STS/etc dance if connection is reused and has TLS negotiated already. Therefore this change cannot be implemented transparently on smtpconn level and must be implemented in remote module.
3. Currently "concurrency" limiting is implemented in terms of parallel SMTP transactions (message deliveries). We need to think if we want to change anything here.

**Comment by wjywbs** [comment]
For example, "Yahoo Mail accepts a maximum of 20 messages per SMTP connection."
https://help.yahoo.com/kb/guidelines-establishing-smtp-connections-yahoo-mail-sln3433.html

I think the reset command can be used when reusing a connection.

**Comment by foxcpp** [comment]
>I think the reset command can be used when reusing a connection.

RSET command has a specific use case of aborting existing SMTP transaction. Strictly speaking it is not even valid to use without an active transaction (per RFC 5321). Idle connections are supposed to not have any transaction running anyway. NOOP command here is used to detect any connection issues or closure on the other send during idle time.

**Comment by foxcpp** [comment]
>For example, "Yahoo Mail accepts a maximum of 20 messages per SMTP connection."
>https://help.yahoo.com/kb/guidelines-establishing-smtp-connections-yahoo-mail-sln3433.html

I wonder if anyone reading this has more information on similar limits that may be imposed by other big providers.

**Comment by wjywbs** [comment]
```
   The receiver MUST send a "250 OK" reply to a RSET command with no arguments.

 A reset command may be issued by the client at any time.  It is
   effectively equivalent to a NOOP (i.e., it has no effect) if issued
   immediately after EHLO, before EHLO is issued in the session, after
   an end of data indicator has been sent and acknowledged, or
   immediately before a QUIT.  An SMTP server MUST NOT close the
   connection as the result of receiving a RSET; that action is reserved
   for QUIT (see Section 4.1.1.10).
```

https://tools.ietf.org/html/rfc5321#section-4.1.1.5

**Comment by foxcpp** [comment]
Ah, okay, so I remembered that bit wrong.
