### ISSUE TITLE
Strange behaviour with FairEmail Android mail client

### ISSUE THREAD

**Issue by yesnomaybeyes** [foxcpp/maddy#240]
Hi!

![image](https://user-images.githubusercontent.com/28198579/84601740-627fb080-ae7a-11ea-91b9-e6bfcb8a701a.png)

I've been getting a weird warning with the FairEmail mail client when refreshing a folder inside it. Folder listings/IMAP keywords/syncing/sending and receiving email all work fine, but the warning persists.

I was talking to the author of FairEmail regarding the warning to identify the cause as FairEmail works with my 9 other email accounts and I hoped their own analysis would save you time, their response is below after I gave them a test account:

> 
> There are at least protocol bugs because moving (=copy+delete) to the trash folder didn't work as expected.
> 
> 06-14 15:26:18.409 13182 30271 I System.out: FX104 STORE 3 +FLAGS (\Deleted)
> 06-14 15:26:18.425 13182 30271 I System.out: FX104 OK STORE completed
> 06-14 15:26:18.466 13182 30271 I System.out: FX106 EXPUNGE
> 06-14 15:26:18.514 13182 30271 I System.out: FX106 OK EXPUNGE completed
> 06-14 15:26:18.515 13182 30269 I System.out: FX107 IDLE
> 06-14 15:26:18.516 13182 30269 I System.out: * 3 EXPUNGE
> 
> Yet:
> 
> 06-14 15:26:18.791 13182 16353 I System.out: JT3 FETCH 3 (UID)
> 06-14 15:26:18.806 13182 16353 I System.out: JT3 OK FETCH completed
> 
> JavaMail doesn't handle this properly by returning a uid of -1, but that is another problem.
> 

I hope that is somewhat helpful to you.

I really want to move my current setup to Maddy, I have several domains with 30+ mailboxes, with my main mailbox being 99k emails.

**Comment by foxcpp** [comment]
Okay, so gist of the problem is that message is COPY+Delete'd and then it does not appear in the target mailbox?
Is there any chance I can see the full client log so I will have a better chance at reproducing this exact issue?

**Comment by yesnomaybeyes** [comment]
Hi,

I think so... the actual observable issue I have is that JavaMail (which FairEmail uses) throws warnings of `NO imap: bad sequence set value "-1", that message appears to originate from the go-imap library, as to where the actual issue is, I'm not entirely sure. FairEmail works with many other providers (I use it on my current dovecot+postfix setup mainly) without any warnings.

I am not doing anything to trigger the issue except forcing the client to sync.

The client is found on F-Droid if it's easier for you to debug "live", but I'm more than happy to have `adb logcat` running while I trigger the issue. Is there any debug flags/parameters I should set on maddy at the same time?

**Comment by foxcpp** [comment]
Okay, I managed to reproduce the issue with FairEmail client. Next step is to write a test case and figure out what is going on.  I guess there is a problem with reference counting (maddy IMAP backend does not actually copy messages on COPY command) that causes both old message and its copy to get removed.

**Comment by foxcpp** [comment]
```go
func TestCopyExpungeLoss(t *testing.T) {
	b := initTestBackend()
	defer cleanBackend(b)
	assert.NilError(t, b.CreateUser(t.Name()))
	usr, err := b.GetUser(t.Name())
	assert.NilError(t, err)
	assert.NilError(t, usr.CreateMailbox(t.Name()))
	mbox, err := usr.GetMailbox(t.Name())
	assert.NilError(t, err)

	assert.NilError(t, usr.CreateMailbox(t.Name()+"tgt"))
	mboxTgt, err := usr.GetMailbox(t.Name() + "tgt")
	assert.NilError(t, err)

	testComplete := "Subject: Test\r\n\r\nBody text"
	assert.NilError(t, mbox.CreateMessage([]string{}, time.Now(), strings.NewReader(testComplete)))
	assert.NilError(t, mbox.CreateMessage([]string{}, time.Now(), strings.NewReader(testComplete)))

	seq, _ := imap.ParseSeqSet("2")
	assert.NilError(t, mbox.CopyMessages(false, seq, mboxTgt.Name()))
	assert.NilError(t, mbox.UpdateMessagesFlags(false, seq, imap.AddFlags, []string{imap.DeletedFlag}))
	assert.NilError(t, mbox.Expunge())

	seq, _ = imap.ParseSeqSet("2")

	ch := make(chan *imap.Message, 2)
	assert.NilError(t, mbox.ListMessages(false, seq, []imap.FetchItem{imap.FetchUid}, ch), "ListMessages")
	assert.Assert(t, is.Len(ch, 1))
	<-ch

	ch = make(chan *imap.Message, 2)
	assert.NilError(t, mboxTgt.ListMessages(false, seq, []imap.FetchItem{imap.FetchUid}, ch), "ListMessages")
	assert.Assert(t, is.Len(ch, 1))
	<-ch
}
```

There we go. This fails with `assertion failed: expected %!s(chan *imap.Message=0xc000068f60) (length 0) to have length 1`.   Very bad it went unnoticed for so long...

**Comment by foxcpp** [comment]
Oh, copy-paste typo in test above, second ParseSeqSet should have "1" argment. And then the test passes.

**Comment by yesnomaybeyes** [comment]
Thanks so much for looking into this. :) I'm looking forward to using maddy.

**Comment by foxcpp** [comment]
Okay, it becomes even more interesting with the fact I cannot reproduce the issue on a clean server install (I previously reproduced on a mail server running for @hexanet.dev). It must have something related to storage state.

**Comment by foxcpp** [comment]
Okay, I identified another issue with EXISTS not reflecting the actual amount of messages in a mailbox. :)

**Comment by foxcpp** [comment]
Basically, EXPUNGE command was not updating message counter for a folder. I believe that is the reason of your actual problem.

**Comment by yesnomaybeyes** [comment]
Ahh! Thank you so much for looking into this, let me know if/when I can test anything.

**Comment by foxcpp** [comment]
@yesnomaybeyes I pushed the fix for message counter problem to the `dev` branch, along with a few other minor fixes. Would appreciate if you try it out. 

That is:
```
$ git clone https://github.com/foxcpp/maddy.git
$ cd maddy
$ git checkout dev
$ ./build.sh # build maddy as usual 
```

If you have an existing database, it may need a little fix using sqlite3 CLI utility:
```
$ sqlite3 /var/lib/maddy/imapsql.db
sqlite> update mboxes set msgsCount = (select count(*) from msgs where mboxId = mboxes.id);
```

I plan to release 0.3.2 with fixes only (current dev branch also includes some new 'experimental' features).

**Comment by yesnomaybeyes** [comment]
Works amazingly now, thank you!

What is the best way to import a Maildir from Dovecot?

**Comment by foxcpp** [comment]
Utilities like https://imapsync.lamiral.info/ and https://github.com/OfflineIMAP/offlineimap can copy messages between IMAP mailboxes on any server. May need some scripting to move big amount of mailboxes but it will preserve all IMAP attributes. You may also try writing a script using `maddyctl imap-msgs add` if you feel like it.

**Comment by foxcpp** [comment]
There is also some work being done to implement maildir-compatible storage backend (see #6) so you would be able to point maddy to existing maildirs and have it "just work".  It is low-priority now though.

**Comment by yesnomaybeyes** [comment]
Thank you!
I think this issue can be closed now. Thanks again for the help.

**Comment by foxcpp** [comment]
[maddy 0.3.2](https://github.com/foxcpp/maddy/releases/tag/v0.3.2) released with corresponding fixes included.
