### ISSUE TITLE
IMAP Threads

### ISSUE THREAD

**Issue by jeefo** [foxcpp/maddy#252]
# Use case

Adding support for IMAP threading and sorting. The only feature that is currently i miss in maddy with my setup...

# Your idea for a solution

Probably enable https://github.com/emersion/go-imap-sortthread for imap-go ?

**Comment by foxcpp** [comment]
First of all, go-imap-sortthread needs server support: https://github.com/emersion/go-imap-sortthread/issues/1

Then go-imap-sql (maddy's backend) should implement corresponding interfaces. I do not see SORT as something complicated - all sort keys allowed by RFC are already in backend's static cache. THREAD might need some more work but we probably can start with naive algorithm referred to as ORDEREDSUBJECT in RFC. It would produce "good enough" output in most cases.

**Comment by foxcpp** [comment]
Ref. https://github.com/emersion/go-imap-sortthread/pull/9
