### ISSUE TITLE
Code license change

### ISSUE THREAD

**Issue by foxcpp** [foxcpp/maddy#253]
I have some thoughts regarding changing maddy's source code license. Frankly, I never thought I would make it that far and MIT license was always my "don't care" choice for small projects and it was the license picked by @emersion, likely for the same reason. It is hard to call maddy a small project now, right?
In other words, I now want at least my future work to remain in open-source due to the amount of effort I am putting into it. Therefore, I am considering changing current license (MIT) to GPLv3. 

* Currently existing releases will remain MIT-licensed as there is no legal path for me to revoke it neither I want to bother rewriting history. maddy ~~0.3.3~~, 0.4 and all future releases will be distributed under terms of the GPLv3 license.
* Supplementary libraries I wrote for use in maddy (including go-imap-sql backend and go-imap-backend-tests suite) will continue using MIT license. I will still try to extract parts of maddy code base into such MIT-licensed libraries for wider use (still hoping to get around to upstream DMARC check code to go-msgauth).
* I am not intending to act hostile towards business that may want benefit from maddy project in the future. That is the reason I am not selecting AGPL license - if you modify maddy for your own needs and provide email service, I am completely fine with that.
* I am concerned about how that might affect upcoming work to create public API for third-party modules. Changing license to GPLv3 will require such extensions to be also GPLv3 since they will need to use some of maddy's code.
* ~~I believe I do not need to ask each of 13 contributors to agree on license change since MIT license itself allows "anyone" (including me, that is) to "sublicense" software.~~

I would like to hear any opinions regarding my plans from that small community I managed to build so far.
CC @emersion @Hexawolf

**Comment by foxcpp** [comment]
Nobody voiced any opinions, moving forward with the change...

**Comment by emersion** [comment]
+1 from me

>I believe I do not need to ask each of 13 contributors to agree on license change since MIT license itself allows "anyone" (including me, that is) to "sublicense" software.

Hmm. However I don't know whether you can drop the MIT license. Including both would be fine, but the MIT license says the copyright notice must be retained.

**Comment by foxcpp** [comment]
> Hmm. However I don't know whether you can drop the MIT license. Including both would be fine, but the MIT license says the copyright notice must be retained.

The only copyright notice we had there is LICENSE so I moved it to docs with a small note: https://github.com/foxcpp/maddy/blob/dev/docs/LICENSE.old

**Comment by Avamander** [comment]
> +1 from me
> 
> >I believe I do not need to ask each of 13 contributors to agree on license change since MIT license itself allows "anyone" (including me, that is) to "sublicense" software.
> 
> Hmm. However I don't know whether you can drop the MIT license. Including both would be fine, but the MIT license says the copyright notice must be retained.

He can drop it if he's the single license owner, if he isn't, he has to ask for permission. This would also be the neatest solution for files he's sole the contributor.

It's also probably a good idea to clearly indicate which files are MIT (and making new files clearly GPL) using license headers.

**Comment by emersion** [comment]
>He can drop it if he's the single license owner, if he isn't, he has to ask for permission. This would also be the neatest solution for files he's sole the contributor.

That's not the case. All contributors are copyright holders of their contributions.

>It's also probably a good idea to clearly indicate which files are MIT (and making new files clearly GPL) using license headers.

I don't think it's necessary. All files are GPL'ed from now on, there's no ambiguity.

**Comment by Avamander** [comment]
> That's not the case. All contributors are copyright holders of their contributions.

Exactly, are you not the sole contributor in a single file?

> I don't think it's necessary. All files are GPL'ed from now on, there's no ambiguity.

It's sublicense, not relicense though.

**Comment by foxcpp** [comment]
> It's sublicense, not relicense though.

What would be a practical difference for our case?  The only problem I see is that I cannot get rid of LICENSE.old file - I am required to preserve original copyright notices and warranty disclaimer. So be it, docs/ directory is included in source code distributions so I am complying with MIT license.

**Comment by Avamander** [comment]
> What would be a practical difference for our case? 

https://opensource.stackexchange.com/questions/2644/does-the-mit-licenses-right-to-sublicense-allow-me-to-change-the-license-of-s

**Comment by foxcpp** [comment]
Okay, lets go over our short list of contributors and ask them nicely. Who would take the responsibility to properly formulate the response so it would allow me to use contributed code as if it was initially contributed under GPLv3 terms?

"I grant Maddy Mail Server maintainers right to deal with code and/or documentation contributed by me to the project under terms of the GNU Public License Version 3."
Would that work?

**Comment by Avamander** [comment]
> Would that work?

IANAL, but it should. Based on the git commits, you can relicense everything else you yourself already own.

**Comment by foxcpp** [comment]
>IANAL, but it should. 

Well, I hope nobody of these 12 people would want to sue me.

@emersion :heart: @wjywbs :heart: @bn4t :heart: @lupine :heart: @kk-boop :heart:
@Avamander :heart: @letto4135 @delthas :heart: @amitlevy21 :heart:
@V1A0 :heart: @Hexawolf 
I would appreciate you all copy-pasting the following statement as the comment in this issue so I could sleep safe at night, thanks!

"I grant Maddy Mail Server maintainers right to deal with code and/or documentation contributed by me to the project under terms of the GNU Public License Version 3."

**Comment by Avamander** [comment]
I don't think my few-word change really gives me any rights for them, but okay:

```
I grant Maddy Mail Server maintainers right to deal with code and/or documentation contributed by me to the project under terms of the GNU Public License Version 3.
```

**Comment by bn4t** [comment]
Sure thing.

```
I grant Maddy Mail Server maintainers right to deal with code and/or documentation contributed by me to the project under terms of the GNU Public License Version 3.
```

**Comment by emersion** [comment]
I grant Maddy Mail Server maintainers right to deal with code and/or documentation contributed by me to the project under terms of the GNU Public License Version 3.

**Comment by delthas** [comment]
I grant Maddy Mail Server maintainers right to deal with code and/or
documentation contributed by me to the project under terms of the GNU
Public License Version 3.

**Comment by wjywbs** [comment]
My main concerns about the possible limitations of GPL are:

- Distribute maddy as a part of SMTP software-as-a-service solution to run on premise in business customers, like PowerMTA.
- Distribute maddyctl or proprietary plugins to end users to create mailboxes or manage auth. The plugin situation is similar to nvidia drivers in linux.
- Give an advantage to choose other mail servers such as postalhq/postal and nodemailer. Both of them are under MIT license.

But, considering my contribution to this project is small and you can simply choose to delete my changes in the GPL code if I disagree,

I grant Maddy Mail Server maintainers right to deal with code and/or documentation contributed by me to the project under terms of the GNU Public License Version 3.

I'll keep a copy of the MIT licensed code under my account, push a few patches under MIT and create PR here under GPL.

**Comment by foxcpp** [comment]
> - Distribute maddy as a part of SMTP software-as-a-service solution to run on premise in business customers, like PowerMTA.

I work on options that would enable building software that works **with** maddy without modifying maddy itself. GPLv3 explicitly permits interaction using standard OS mechanisms. Several proprietary products use that loophole by bundling GPL-licensed software and working with it by calling it e.g. via its CLI Interface.

* It is already possible to manage user credentials via shared SQL database
* Prometheus-compatible telemetry endpoint enables statistics collection
* Machine-readable logs enable collection of extended information about server state and messages.
* SMTP filters may be added using de-facto standard protocol - milter
* Extended message processing may be implemented by forwarding to LMTP

We can always work on creating more possibilities for third-party software integration.

> - Distribute maddyctl or proprietary plugins to end users to create mailboxes or manage auth. The plugin situation is similar to nvidia drivers in linux.

I mentioned that in the initial post but yeah, that would restrict extending maddy itself to GPLv3. Which to some extent is the purpose of this license in the first place. 

Note there is an intentional loophole for mailboxes management: go-imap-sql remains MIT, one could directly work with it in the same way maddyctl does it.

> - Give an advantage to choose other mail servers such as postalhq/postal and nodemailer. Both of them are under MIT license.

I agree that may be the reason to pick an alternative implementation if options proposed above do not work for you. I'm not trying to cater to absolutely everyone here.

**Comment by v1a0** [comment]
I'm in, good luck!

I grant Maddy Mail Server maintainers right to deal with code and/or documentation contributed by me to the project under erms of the GNU Public License Version 3.

**Comment by amitlevy21** [comment]
No problem.
```
I grant Maddy Mail Server maintainers right to deal with code and/or documentation contributed by me to the project under terms of the GNU Public License Version 3.
```

**Comment by lupine** [comment]
As far as I'm aware, this isn't needed. That being the case, there's no harm in me saying:

> I grant Maddy Mail Server maintainers right to deal with code and/or documentation contributed by me to the project under terms of the GNU Public License Version 3

:slightly_smiling_face: 

Personally, I'd prefer the project to be AGPL or similar, but my contributions to it are very minor, so I don't expect that to have much weight!

**Comment by kk-boop** [comment]
I grant Maddy Mail Server maintainers right to deal with code and/or
documentation contributed by me to the project under terms of the GNU
Public License Version 3.

**Comment by Hexawolf** [comment]
I grant Maddy Mail Server maintainers right to deal with code and/or documentation contributed by me to the project under terms of the [GNU Public License Version 3](https://www.gnu.org/licenses/gpl-3.0.en.html).

**Comment by foxcpp** [comment]
Okay, we are good to go, I suppose. Changes made by @letto4135 are not substantial enough and it is not Iike they are going to sue us, right?
