### ISSUE TITLE
Feature request mail allias

### ISSUE THREAD

**Issue by martynvdijke** [foxcpp/maddy#257]
# Mail aliases

I am wondering if maddy supports mail allies at the moment ?
So for example a@x.com sends mail to multiple other users b@y.co and c@u.com or something.

I searching around in the repo and I can find issue https://github.com/foxcpp/maddy/issues/18 and commits https://github.com/foxcpp/maddy/commit/7efcd81887fc27e7111ef0e69e0b3660e0c04fab https://github.com/foxcpp/maddy/commit/82ac3359a8f8a080460d89ad2cc448d6e1888779 but I am wondering if this code is still up to date and how to configure it ?
Since there seems to be no documentation of the rewrite (at least from what I can see)

**Comment by foxcpp** [comment]
https://foxcpp.dev/maddy/man/_generated_maddy-filters.5/

>Envelope sender / recipient rewriting (replace_sender, replace_rcpt)
>'replace_sender' and 'replace_rcpt' modules replace SMTP envelope addresses based on the mapping defined by the table module (maddy-tables(5)). Currently, only 1:1 mappings are supported (that is, it is not possible to specify multiple replacements for a single address).

Though indeed maddy-tables(5) is accidentally not included in website render. 

The same paragraph also provides a few examples:
```
modify {
    replace_rcpt file_map /etc/maddy/aliases
    replace_rcpt static {
        entry a@example.org b@example.org
    }
    replace_rcpt regexp "(.+)@example.net" "$1@example.org"
}
```
Though it is somewhat outdated - file_map is now just file.

Also:

>Possible contents of /etc/maddy/aliases in the example above:
```

# Replace 'cat' with any domain to 'dog'.
# E.g. cat@example.net -> dog@example.net
cat: dog

# Replace cat@example.org with cat@example.com.
# Takes priority over the previous line.
cat@example.org: cat@example.com
```

**Comment by foxcpp** [comment]
Also default config is using all the same stuff:
https://github.com/foxcpp/maddy/tree/master/maddy.conf

**Comment by martynvdijke** [comment]
Thank you !
