### ISSUE TITLE
User doesn't exist Error

### ISSUE THREAD

**Issue by kamarya** [foxcpp/maddy#267]
# Describe the bug
By following the tutorial I can not make maddy work. I receive "User doesn't exist (msg ID = aa74c9e5)" while sending from maddy (Apple Mail) and "550 5.1.1 User doesn't exist (msg ID = 6b4ebbc6)" reported while sending to the maddy.

What do you think is wrong?

I followed the instruction here:
 https://foxcpp.dev/maddy/tutorials/setting-up/
an I think it should just work.

I have just changed "dmarc yes" to "**dmarc no**" and commented the "dkim" in local_routing.

# Steps to reproduce

follow https://foxcpp.dev/maddy/tutorials/setting-up/
# Log files

# Configuration file

```
msgpipeline local_routing {
    dmarc no
    check {
        require_matching_ehlo
        require_mx_record
#        dkim
        spf
    }
```

# Environment information

* maddy version: 0.4.0+gf9d5c0c

**Comment by foxcpp** [comment]
Note there are two maddyctl commands required to create a user account, one saves credentials for IMAP/Submission use and second one creates IMAP mailbox.

Second command is:
```
maddyctl imap-acct create postmaster@example.org
```

**Comment by kamarya** [comment]
@foxcpp thanks for quick reply. I had a look at https://foxcpp.dev/maddy/man/_generated_maddy-smtp.5/ and played with
```
        destination example.org {
            deliver_to &local_mailboxes
        }
        default_destination {
            reject
        }
```

by putting above in `default_source` now I can receive email. I think SMTP config instructions should be updated and added to the tutorial. Note that by simply following the content of the  above link the service does not start.

**Comment by foxcpp** [comment]
I am able to use default configuration by specifying correct TLS cert path and domains. 

In this config:
1. smtp endpoint has the following snippet
```
destination postmaster $(local_domains) {
    deliver_to &local_routing
}
default_destination {
    reject 550 5.1.1 "User doesn't exist"
}
```

2. local_routing block has the following:
```
destination postmaster $(local_domains) {
    ...
    deliver_to &local_mailboxes
}

default_destination {
    reject 550 5.1.1 "User doesn't exist"
}
```

Together this means messages on port SMTP 25 for all domains specified in local_domains are sent to local_mailboxes which is imapsql storage.

**Comment by kamarya** [comment]
@foxcpp I have done the changes according to the tutorial. On top of the configuration file I have changed

```
$(hostname) = my-domain.net
$(primary_domain) = mail.my-domain.net
$(local_domains) = $(primary_domain)

tls file /etc/letsencrypt/live/mail.my-domain.net/fullchain.pem /etc/letsencrypt/live/mail.my-domain.net/privkey.pem
``` 

and the owner of `etc/letsencrypt/live/mail.my-domain.net` is `maddy:maddy` ... Apple Mail can connect/receive to IMAP with the creds. As I said the only difference is that I set `dmarc no` and I have commented `dkim`.

Now I get `""reason":"reject directive used","smtp_code":554,"smtp_enchcode":"5.7.0","smtp_msg":"Message rejected due to a local policy"` error while sending. How can I fix this?

I suppose the `tls` config on top is global ?
DKIM string with `k=rsa` is too long for my domain register. How can I use something shorter like the example `k=ed25519` ?

**Comment by foxcpp** [comment]
You seem to have hostname and primary_domain mixed up.

**Comment by foxcpp** [comment]
Just noticed, your configuration would make mail.my-domain.com work as domain.

**Comment by foxcpp** [comment]
If you have an idea how to make tutorial better about this detail - you are free to submit any edits.

**Comment by kamarya** [comment]
thank you. I could make it working using mostly the default configuration. How can I change DKIM key algorithm to something shorter (and probably weaker) ? I can not add TXT record cause it is too long with the default generated DKIM string.

**Comment by foxcpp** [comment]
The line you commented out is dkim verification on inbound delivery.  There is modify -> dkim line in submission block. It is the one that does signing.

You may try using ed25519:
```
dkim ... {
    newkey_algo ed25529
}
```
(And remove existing key to regenerate it)
This will definitely fit but it is not widely supported by recipients.

Alternatively, you can try generating RSA-1024. maddy does not accept "rsa1024" in newkey_algo for security reasons so you are on your own to generate both files. .key one is just PEM private key.

**Comment by foxcpp** [comment]
```
openssl genrsa -des3 -out private.pem 1024
openssl rsa -in private.pem -outform PEM -pubout -out public.pem 
```
This should give you necessary files. private.key goes into .key and base64 in public.pem is what should be in k=

**Comment by foxcpp** [comment]
And you should contact your provider about this since they are preventing you from using a reasonably secure algorithm for DKIM signing.

**Comment by kamarya** [comment]
agreed.
