### ISSUE TITLE
How to do DKIM signature by rspamd?

### ISSUE THREAD

**Issue by acim** [foxcpp/maddy#281]
# Describe the bug

I am not sure something is wrong, but I don't know how to to DKIM signature by rspamd and not by maddy?

In default maddy configuration I found the line which does DKIM:

```
        default_destination {
            modify {
                dkim $(primary_domain) $(local_domains) dkim
            }
            deliver_to &remote_queue
        }
```

But I would like to comment it out and let rspamd do this

**Comment by foxcpp** [comment]
check.rspamd module currently does not support insertion of arbitrary headers by rspamd since it does not interpret milter actions in server response.
You want to configure it using check.milter, that is, with rspamd being used via milter protocol.

Related rspamd doc: https://rspamd.com/doc/workers/rspamd_proxy.html
And your can find check.milter reference doc here: https://foxcpp.dev/maddy/man/_generated_maddy-filters.5/
Most likely you want to replace modify{} block with:
```
check {
  milter tcp://127.0.0.1:11332
}
```

**Comment by acim** [comment]
This works in a sense, although there are at least 2 big problems.

After I set maddy according to your description, I got the following error:

```
❯ kubectl logs maddy-786dcccf9d-8xs8j 
smtp: listening on tcp://0.0.0.0:25	
/data/maddy.conf:154: module check.milter () doesn't implement module.Check interface
```

I checked the code and really module check.milter has method CheckStateForMsg but it lacks context.Context to satisfy the module.Check interface:

```
CheckStateForMsg(ctx context.Context, msgMeta *MsgMetadata) (CheckState, error)
```

I see no purpose of having context.Context here because it is not used in any implementation of module.Check but I added it and tried again, but now I got the following error from maddy:

```
submission: RCPT error	{"effective_rcpt":"john.doe@gmail.com","msg_id":"f4b31178","john.doe@gmail.com","reason":"milter: negotiate: optneg read: EOF"}
```

rspamd reports the following error:

```
2020-10-11 12:00:28 #7(rspamd_proxy) <0ae62e>; proxy; proxy_accept_socket: accepted milter connection from 10.0.0.152 port 51896
2020-10-11 12:00:28 #7(rspamd_proxy) <0ae62e>; milter; rspamd_milter_process_command: MTA specifies too old protocol: 2, aborting connection
2020-10-11 12:00:28 #7(rspamd_proxy) <0ae62e>; proxy; proxy_milter_error_handler: abnormally closing milter connection from: 10.0.0.152:51896, error: invalid protocol version: 2
```

**Comment by acim** [comment]
It seems that github.com/emersion/go-milter is just outdated :(

**Comment by foxcpp** [comment]
Milter protocol versioning is a mess. I suppose we can get away by claiming to support protocol version 6.

**Comment by foxcpp** [comment]
You can add the following line to go.mod:
```
replace github.com/emersion/go-milter => github.com/foxcpp/go-milter client-v6
```
And build maddy.

I patched it to pretend to support version 6 - in fact it kind of supports it already, but I decided to play it safe.

Waiting for your results and then I will see if this version bump should be upstreamed.

**Comment by foxcpp** [comment]
CC @emersion

**Comment by acim** [comment]
maddy

```
submission: incoming message	{"msg_id":"769cb7a0","sender":"john.doe@example.com","src_host":"[192.168.1.102]","src_ip":"123.123.123.123:58276","username":john.doe@example.com"}
submission: RCPT error	{"check":"milter","effective_rcpt":"john.doe@gmail.com","milter":"tcp://rspamd:11332","msg_id":"769cb7a0","rcpt":"john.doe@gmail.com","reason":"milter: conn: action read: read tcp 10.0.0.56:42766-\u003e10.108.227.21:11332: i/o timeout","smtp_code":451,"smtp_enchcode":"4.7.1","smtp_msg":"I/O error during policy check"}
submission: aborted	{"msg_id":"769cb7a0"}
```

rspamd

```
2020-10-12 02:45:26 #7(rspamd_proxy) <39a128>; proxy; proxy_accept_socket: accepted milter connection from 10.0.0.56 port 42766
2020-10-12 02:45:26 #7(rspamd_proxy) <39a128>; milter; rspamd_milter_process_command: got connection from 123.123.123.123:58276
2020-10-12 02:45:36 #7(rspamd_proxy) <39a128>; proxy; proxy_milter_finish_handler: finished milter connection
```

I need something robust so I probably have to switch to Postfix + Dovecot. Thank you for your help.

**Comment by foxcpp** [comment]
Okay.

Replaced by #283.
