### ISSUE TITLE
Disable reloading

### ISSUE THREAD

**Issue by bclermont** [foxcpp/maddy#284]
I'm running with debug log level. and I see every few seconds a reloading of files and certs.
Those files changes once every few months. I wonder if we can just disable reload and read those files at startup and reload at next restart?

**Comment by foxcpp** [comment]
It is definitely possible to improve it by watching for file changes instead of unconditional reloading. Though it may reduce compatibility with FSs. 

I assume the particular problem you are having is debug log spam, is that right?

**Comment by bclermont** [comment]
please delete that repo as this is pure trash
