### ISSUE TITLE
Add timestamps to logs

### ISSUE THREAD

**Issue by bclermont** [foxcpp/maddy#285]
When I run in debug mode I have the following outputs:

```
[debug] table.file: reloading	
[debug] tls.loader.file: reloading certs	
[debug] table.file: reloading
```

As there is no timestamp, it's not very useful to look at past events and correlate with issues.

**Comment by foxcpp** [comment]
```
log stderr_ts
```
Is what you are looking for.

Default configuration assumes that stderr is recorded by journaling daemon that will add its own timestamps.

**Comment by bclermont** [comment]
It works, thanks!
