### ISSUE TITLE
Missing cases in switch statements

### ISSUE THREAD

**Issue by hugmouse** [foxcpp/maddy#288]
Missing cases in switch of type `milter.ActionCode`: `ActTempFail` and `ActReplyBody`

https://github.com/foxcpp/maddy/blob/1c42a705334b3d34b4b3ddff74c654773a4c0ef5/internal/check/milter/milter.go#L131-L173

---

`ResultNone` in

https://github.com/foxcpp/maddy/blob/1c42a705334b3d34b4b3ddff74c654773a4c0ef5/internal/dmarc/evaluate.go#L137-L141

---

`PolicyNone` in 

https://github.com/foxcpp/maddy/blob/1c42a705334b3d34b4b3ddff74c654773a4c0ef5/internal/msgpipeline/check_runner.go#L292-L319

**Comment by foxcpp** [comment]
Last two are intended. If you feel like it - you can make a PR to add empty case.

First one needs more careful look.

**Comment by foxcpp** [comment]
Thanks for the report!
