### ISSUE TITLE
Refactor imapsql blob storage interface to use modules framework

### ISSUE THREAD

**Issue by foxcpp** [foxcpp/maddy#303]

**Comment by jmthackett** [comment]
Hey, I'm interested in this and #304 and thinking about doing some work on it. I'm assuming that this file (and especially, the linked struct) are the key ones for this:

https://github.com/foxcpp/maddy/blob/d8cabb932d9e7c3abd056fefe2a7a622e2abf6bd/internal/storage/imapsql/imapsql.go#L62

Am I right in saying the idea here would be to make the backend more generic, with an end result being that maddy's index stays in an rdbms but the message bodies (which I think are stored as blobs?) can go into a backend which might be a database or might be s3?

Edit: sorry, just saw #279, will look at `go-imap-sql`

**Comment by foxcpp** [comment]
This issue is about changing how ExternalStore is set in Init method in the file you referenced.

My idea is to use module framework circuitry since that will give the most flexibility and the most clean separation.

This is a pretty complicated change that requires good knowledge of maddy inner workings.

**Comment by foxcpp** [comment]
Basically, it boils down to the following:
1. Add needed interface to framework/module package (copy go-imap-sql interface?)
2. Add helper function to framework/config/module/interfaces.go
3. Update imapsql's Init function to read some config directive as a module reference using helper added at step 2 (see how other modules do that for inspiration?)
4. Write needed modules implementing needed kinds of "stores"
5. Add hacks to Init for backward compatibility with existing configs

If you are willing to try working on it - feel free to ask guidance on any part. Or just let me know and I will try to take a look at it this weekend (probably leaving S3 store support only which should be then trivial to add).

**Comment by jmthackett** [comment]
I'll have a go at this over the next few days I think; those instructions are enough to start with. I'll open a WIP PR as soon as I can. I'm not amazingly confident but I'll try to get something working.

**Comment by jmthackett** [comment]
It feels reasonable to say I've not had chance to work on this yet, life has somewhat got away from me. I'm now going to move house too, so probably won't have chance to revisit this for a while. Sorry!

**Comment by foxcpp** [comment]
Okay. Take your time.

**Comment by foxcpp** [comment]
Necessary changes are done, the remaining bit is adding new store implementations.
