### ISSUE TITLE
[Document outdated] creating users cmd on dockerhub's overview

### ISSUE THREAD

**Issue by yanyaoer** [foxcpp/maddy#310]
https://hub.docker.com/r/foxcpp/maddy

```
Creating users:

- docker run --rm -it -v maddydata:/data --entrypoint /bin/maddyctl foxcpp/maddy:latest users create foxcpp@maddy.test
+ docker run --rm -it -v maddydata:/data --entrypoint /bin/maddyctl foxcpp/maddy:latest creds create foxcpp@maddy.test
```

**Comment by hugmouse** [comment]
I think we should update this to `docker exec -it maddy maddyctl creds create foxcpp@maddy.test`

**Comment by foxcpp** [comment]
Fixed, @hugmouse it is actually both `creds` and `imap-accts` since they are managed separately since 0.3.

**Comment by espressoelf** [comment]
Coming from [Docker Hub](https://hub.docker.com/r/foxcpp/maddy) to report this being an issue again: the first command to create the user is written as
`docker run --rm -it -v maddydata:/data --entrypoint /bin/maddyctl foxcpp/maddy:latest users create foxcpp@maddy.test`
but should be
`docker run --rm -it -v maddydata:/data --entrypoint /bin/maddyctl foxcpp/maddy:latest creds create foxcpp@maddy.test`
as OP mentioned (`users` vs `creds`).

**Comment by foxcpp** [comment]
Fixed. Sorry about that.
