### ISSUE TITLE
[FreeBSD] build.sh: line 549: hb:p:d:: command not found

### ISSUE THREAD

**Issue by B-Interactive** [foxcpp/maddy#313]
# Describe the bug

On FreeBSD 12.2-RELEASE amd64, when trying to build from source, immediately fails with error:
`./build.sh: line 549: hb:p:d:: command not found`

# Steps to reproduce

1. Fresh install of FreeBSD 12.1 updated to 12.2-RELEASE.
2. Build and install Go 1.15.5 from ports.
3. Build and install Bash shell 5.0.18 from ports.
4. Downloaded and extracted maddy 0.4.2 release from https://github.com/foxcpp/maddy/releases
5. In the extracted folder, I run `bash ./build.sh`
6. Immediately fails with error `./build.sh: line 549: hb:p:d:: command not found`

# Environment information

* FreeBSD version: 12.2-RELEASE amd64
* maddy version: 0.4.2 Release
* Go version: 1.15.5 freebsd/amd64
* Bash shell version: 5.0.18

**Comment by hugmouse** [comment]
Can confirm

![image](https://user-images.githubusercontent.com/44648612/100960812-014cb600-355c-11eb-931f-d7d99501c661.png)

## upd

FreeBSD's `getopt` does not support `-o` parameter 

## upd 2

It seems that using `getopts` should be better option

According to [Bash FAQ 35](https://mywiki.wooledge.org/BashFAQ/035):
> Unless it's the version from util-linux, and you use its advanced mode, never use getopt(1). getopt cannot handle empty > arguments strings, or arguments with embedded whitespace. Please forget that it ever existed.
>
> The POSIX shell (and others) offer getopts which is safe to use instead.

Source: https://stackoverflow.com/questions/2721946/cross-platform-getopt-for-a-shell-script/2728625#2728625

**Comment by B-Interactive** [comment]
Installing [getopt](https://www.freshports.org/misc/getopt/) from ports provides the GNU extensions required by `build.sh`.

To force its use, in `build.sh` I modified line 3 to point to the specific path of the port version of `getopt`:
```
options=$(/usr/local/bin/getopt -o hb:p:d: -l help,builddir:,prefix:,destdir:,systemddir:,configdir:,statedir:,runtimedir:,fail2bandir:,tags:,prefix:,gitversion:,version:,source:,sudo -- "$@")
```

I'm not out of the woods yet with FreeBSD issues.  I now encounter the error below, but I'll research that a little more before following up on it.  I'll mark this specific issue closed given the above appropriate fix.
```
...
--- Preparing integration files...
install: target `vim/ftdetect/maddy-conf.vim' is not a directory
usage: install [-bCcpSsUv] [-f flags] [-g group] [-m mode] [-o owner]
               [-M log] [-D dest] [-h hash] [-T tags]
               [-B suffix] [-l linkflags] [-N dbdir]
               file1 file2
       install [-bCcpSsUv] [-f flags] [-g group] [-m mode] [-o owner]
               [-M log] [-D dest] [-h hash] [-T tags]
               [-B suffix] [-l linkflags] [-N dbdir]
               file1 ... fileN directory
       install -dU [-vU] [-g group] [-m mode] [-N dbdir] [-o owner]
               [-M log] [-D dest] [-h hash] [-T tags]
               directory ...
```

# Update 1

I've yet to produce a happy `build.sh` on FreeBSD, but the above issue and others that would follow are resolved by converting some commands to a FreeBSD variant.

For example, lines [410-412](https://github.com/foxcpp/maddy/blob/1bfaa3995b7a2f23b22b4e2af21c4460852451e1/build.sh#L410-L417) are modified to the following:
```
install -dm 0644 -D "$PKGDIR/$PREFIX/share/vim/vimfiles/ftdetect/" vim/ftdetect/maddy-conf.vim
install -dm 0644 -D "$PKGDIR/$PREFIX/share/vim/vimfiles/ftplugin/" vim/ftplugin/maddy-conf.vim
install -dm 0644 -D "$PKGDIR/$PREFIX/share/vim/vimfiles/syntax/" vim/syntax/maddy-conf.vim

install -dm 0644 -D "$PKGDIR/$FAIL2BANDIR/jail.d/" fail2ban/jail.d/
install -dm 0644 -D "$PKGDIR/$FAIL2BANDIR/filter.d/" fail2ban/filter.d/
    
install -dm 0644 "$PKGDIR/$PREFIX/lib/systemd/system/" systemd/
```

[Line 427](https://github.com/foxcpp/maddy/blob/1bfaa3995b7a2f23b22b4e2af21c4460852451e1/build.sh#L427) becomes:
```
install -dm 0644 "$MADDY_SRC/" "$PKGDIR/$CONFDIR/maddy.conf"
```

Linux `useradd` is switched to FreeBSD's `pw` on line [484 and 486](https://github.com/foxcpp/maddy/blob/1bfaa3995b7a2f23b22b4e2af21c4460852451e1/build.sh#L484-L486):
```
if [ "$elevate" -eq 1 ]; then
   sudo pw user add maddy -n maddy -s /nonexistent -d /var/lib/maddy/
else
   pw user add maddy -n maddy -s /nonexistent -d /var/lib/maddy/
fi
```


Where I've become stumped is these sections, I haven't yet been able to resolve (unchanged original quoted here).  I'm about ready to throw in the towel and try a Linux option.
[Lines 419-423](https://github.com/foxcpp/maddy/blob/1bfaa3995b7a2f23b22b4e2af21c4460852451e1/build.sh#L419-L423):
```
sed -Ei "s!/usr/bin!$PREFIX/bin!g;\
   s!/usr/lib/maddy!$PREFIX/lib/maddy!g;\
   s!/etc/maddy!$CONFDIR!g" "$PKGDIR/$SYSTEMDUNITS/system/maddy.service" "$PKGDIR/$SYSTEMDUNITS/system/maddy@.service"

popd >/dev/null
```

[Lines 471-473](https://github.com/foxcpp/maddy/blob/1bfaa3995b7a2f23b22b4e2af21c4460852451e1/build.sh#L471-L473):
```
    sudo install -Dm "$(stat -c '%a' "$f")" "$f" "$DESTDIR/$f"
else
    install -Dm "$(stat -c '%a' "$f")" "$f" "$DESTDIR/$f"
