### ISSUE TITLE
[OpenBSD] build.sh: getopt: unknown option -- l

### ISSUE THREAD

**Issue by B-Interactive** [foxcpp/maddy#314]
# Describe the bug

On OpenBSD 6.8 amd64, when trying to build from source, immediately fails with error:
```
bash-5.0# ./build.sh
getopt: unknown option -- l
Unknown option: . See --help.
```

# Steps to reproduce

1. Fresh install of OpenBSD 6.8 amd64.
2. Install Go 1.15.2 from packages.
3. Install Bash shell 5.0.18 from packages.
4. Downloaded and extracted maddy 0.4.2 release from https://github.com/foxcpp/maddy/releases
5. In the extracted folder, I run bash ./build.sh
6. Immediately fails with error:
```
bash-5.0# ./build.sh
getopt: unknown option -- l
Unknown option: . See --help.
```
7. Using the --help argument as suggested, produces the same error:
```
bash-5.0# ./build.sh --help
getopt: unknown option -- l
Unknown option: . See --help.
```

# Environment information

* OpenBSD version: 6.8 amd64
* maddy version: 0.4.2 Release
* Go version: 1.15.2
* Bash shell version: 5.0.18

**Comment by foxcpp** [comment]
Unfortunately, current version of build script is rather Linux-specific, in particular getopt is assumed to have GNU extensions.

You can still build maddy by directly calling go tool:
```
go build ./cmd/maddy
go build ./cmd/maddyctl
```

**Comment by B-Interactive** [comment]
Thanks @foxcpp, that provided some more options.

I was able to build it using those two commands you offered.  Skimming through `build.sh` though, it seems there's much more going on than just a build, so if I pursue that option I'll need to nut that all out.

The second thing I tried (again thanks to your pointers), was a version of getopt with GNU extensions.
```
# pkg_add gnugetopt
quirks-3.440 signed on 2020-12-03T21:39:27Z
gnugetopt-1.1.6p2: ok
```

That I believe solves the issue I opened here for OpenBSD ([might test with FreeBSD too](https://github.com/foxcpp/maddy/issues/313)).  However, I stumbled across a new issue that may be specific to Go on OpenBSD (still investigating): `-buildmode=pie not supported on openbsd/amd64`

```
bash-5.0# ./build.sh
                                _|        _|
_|_|_|  _|_|      _|_|_|    _|_|_|    _|_|_|  _|    _|
_|    _|    _|  _|    _|  _|    _|  _|    _|  _|    _|
_|    _|    _|  _|    _|  _|    _|  _|    _|  _|    _|
_|    _|    _|    _|_|_|    _|_|_|    _|_|_|    _|_|_|
                                                    _|
 All-in-one composable mail server.             _|_|

--- Using system Go toolchain (1.15.2, /usr/local/bin/go).
--- WARNING: Source tree is not a Git repository and no version specified.
--- Downloading dependencies...
go: downloading github.com/foxcpp/go-mockdns v0.0.0-20200531120619-ae750bbf9d73
--- Building main executable...
-buildmode=pie not supported on openbsd/amd64
```

Opened a new issue: #315

**Comment by B-Interactive** [comment]
To resolve this specific issue under OpenBSD, install gnugetopt.
```
# pkg_add gnugetopt
```

Then on the line 3 of `build.sh`, modify the command so `getopt` becomes `gnugetop`:
```
options=$(gnugetopt -o hb:p:d: -l help,builddir:,prefix:,destdir:,systemddir:,configdir:,statedir:,runtimedir:,fail2bandir:,tags:,prefix:,gitversion:,version:,source:,sudo -- "$@")
```

**Comment by foxcpp** [comment]
I just pushed 4ec6eb2  with new (much more simple) build.sh implementation. I would appreciate someone testing it on *BSD to make sure it works there correctly. It should work fine with any POSIX shell, not just Bash.
