### ISSUE TITLE
[OpenBSD] -buildmode=pie not supported on openbsd/amd64

### ISSUE THREAD

**Issue by B-Interactive** [foxcpp/maddy#315]
# Describe the bug

When building maddy via `build.sh`, it fails with the error `-buildmode=pie not supported on openbsd/amd64`:

# Steps to reproduce

_`build.sh` (at the time of writing this) has existing issues on BSD systems, related to the version of `getopt` native to those systems, that doesn't support the necessary GNU extensions.  As such, `gnugetopt` must be installed and referenced in order to get this far.  Details below._

1. Install `go` from packages.
2. Install `bash` from packages.
3. Install `gnugetopt` from packages.
4. Modify `build.sh` so line 3 references `gnugetopt` instead of `getopt`.
```
options=$(gnugetopt -o hb:p:d: -l help,builddir:,prefix:,destdir:,systemddir:,configdir:,statedir:,runtimedir:,fail2bandir:,tags:,prefix:,gitversion:,version:,source:,sudo -- "$@")
```
5. Run `./build.sh`: 
```
# bash ./build.sh
```
6. Build fails with error:
```
bash-5.0# ./build.sh
                                _|        _|
_|_|_|  _|_|      _|_|_|    _|_|_|    _|_|_|  _|    _|
_|    _|    _|  _|    _|  _|    _|  _|    _|  _|    _|
_|    _|    _|  _|    _|  _|    _|  _|    _|  _|    _|
_|    _|    _|    _|_|_|    _|_|_|    _|_|_|    _|_|_|
                                                    _|
 All-in-one composable mail server.             _|_|

--- Using system Go toolchain (1.15.2, /usr/local/bin/go).
--- WARNING: Source tree is not a Git repository and no version specified.
--- Downloading dependencies...
go: downloading github.com/foxcpp/go-mockdns v0.0.0-20200531120619-ae750bbf9d73
--- Building main executable...
-buildmode=pie not supported on openbsd/amd64
```

# Environment information

* OpenBSD version: 6.8 amd64
* maddy version: 0.4.2
* go version: 1.15.2
* gnugetopt version: 1.1.6p2
* bash version: 5.0.18

# Notes

There was apparently a patch for Go that would appear to have enabled `buildmode=pie` on OpenBSD, for Go 1.11.  Seems strange it's cropping up here given that.
[cmd/go: static linking fails on OpenBSD 6.2](https://github.com/golang/go/issues/20508#issuecomment-346708910)

**Comment by foxcpp** [comment]
New build.sh script does not unconditionally use -buildmode=pie so this issue can be considered resolved.
