### ISSUE TITLE
Generic conditions and filtering for SMTP pipeline

### ISSUE THREAD

**Issue by foxcpp** [foxcpp/maddy#32]
### Generic conditions syntax
```
value operator value
```

Value can be either variable prefixed with `$` or 

Variable can be *all fields from DeliveryContext* and also any key from DeliveryContext.Ctx. If the variable doesn't exist - its value assumed to be an empty string. 

The operator is one of the following:
* `=` **Variable value must be exactly equal to the value in condition.**
* `=*` Similar to the `=` but is case-insensitive.
* `!=` **Inverted `=`.**
* `!=*` Inverted `=*`.
* `~`  **Value is a regexp that should match variable value.**
* `~*` Case-insensitive version of `~`.
* `!~` **Inverted `~`.**
* `!~*` Inverted `~*`

Inspired by the [nginx's if]. I highlighted operations currently implemented for the `match` block.

Variable value is converted into string before comparsion.

#### Examples

```
$rcpt_domain = "emersion.fr"
$src_ip ~ "^192\.168\..+"
```

### `match` => `if`

Rename `match` block into `if` and make it use conditions syntax described above.

#### Examples

```
if $rcpt_domain = "emersion.fr" {
  proxy smtp://0.0.0.0
}
```

[nginx's if]: https://nginx.org/en/docs/http/ngx_http_rewrite_module.html#if

**Comment by emersion** [comment]
>Generic conditions syntax
>match => if

LGTM

>This filtering is necessary due to the fall-through nature of the pipeline (deliver statement does not stop processing).

Ugh, don't we have a `stop` directive too?

>As a consequence, in the following example, maddy MTA will connect to itself and deliver email twice.

Hmm, I don't get why? If it takes a branch, it won't take the other?

>deliver [filter conditions] target [options]

Maybe it'll be worth it to use an alternate form to filter, e.g.:

```
deliver {
    filter <filter1> <filter2>
    target <target>
}
```

>Combined examples

Seems like there are duplicate conditions/filters here

**Comment by foxcpp** [comment]
>Hmm, I don't get why? If it takes a branch, it won't take the other?

Let's say we are emersion.fr and we got a message with two recipients: foxcpp@foxcpp.dev and contact@emersion.fr.
And we have this pipeline definition:
```
submission smtps://0.0.0.0 {
  hostname emersion.fr
  if rcpt_domain = "emersion.fr" {
    deliver local
  }
  if rcpt_domain != "emersion.fr" {
    deliver remote
  }
}
```

`if rcpt_domain = "emersion.fr"` => true (contact@emersion.fr), execute subblock
`deliver local` => local delivery module gets message with two recipients (problem 1)

`if rcpt_domain != "emersion.fr"` => true (foxcpp@foxcpp.dev), execute subblock
`deliver remote` => remote delivery modue gets message with two recipients (problem 2)

```
   {
    deliver local
  }
```

#### Problem 1
What should local delivery module do with `foxcpp@foxcpp.dev`? Try to save to local `foxcpp` account? Ignore? Fail because of a non-local domain? 

If we decide to just ignore - we are limiting the flexibility of pipeline functionality (and as a consequence - entire maddy).  What if we have two domains we want to share the same accounts? It would make a lot of sense to have a single mail server for them. This raises a question about how to define what is local and what is not. My proposal solves this in a generic way which also allows describing more complex combinations (like, have different storage for different domains, forward messages for certain accounts to a different server, etc).

#### Problem 2
What should remote delivery module do with `contact@emersion.fr`? Deliver to `emersion.fr` (us, basically). Ignore? Fail because of local domain?

...

While writing that I got another idea how to filter envelope information in pipeline: combine filter definitions with if blocks.

```
if rcpt_domain = "emersion.fr" {
  deliver local  # local delivery module will see only recipients with the local domain
}
if rcpt_domain != "emersion.fr" {
  deliver remote # remote delivery module will see only recipients with non-local domains
}
```


Well, I often come up with suboptimal solutions) What do you think? Perhaps you have a better idea of what to do here.

**Comment by foxcpp** [comment]
Another variant:
Introduce `destination` directive as in #14 and leave `if` for more low-level dispatching.
```
destination emersion.fr { 
  delivery local # sees only recipients with the emersion.fr domain, not called if there are no such recipients
}
```
Here, `destination` argument allows either `emersion.fr` (just recipient domain), `contact@emersion.fr` (full address) or `/regexp/` that should match full address.

**Comment by foxcpp** [comment]
https://github.com/antonmedv/expr

**Comment by foxcpp** [comment]
Reconsidering this proposal in the light of expr library I linked above (which is very good, I think).

Since expression is a single string, it's tempting to just accept it as an argument. This requires it to be wrapped in quotes since the expression will most definitely contain whitespace. This leads to another problem: expr uses quotes for string literals.

This will look quite messy:
```
if "\"foxcpp@example.org\" in To" {
 // ...
}
``` 

Instead, I propose to finally copy config lexer from caddy repo and include it here.
Then, add flag to the token indicating that it was constructed from a quoted string.
This would let users write expressions like that:
```
if "foxcpp@example.org" in To {
}
```
We join arguments, readd quotes stripped by lexer and construct the following expression that then will get passed to expr library: `"foxcpp@example.org" in To`.

Wdyt?

**Comment by emersion** [comment]
Makes sense to me.
