### ISSUE TITLE
Docker image for 0.4.3 doesn't use custom DefaultStateDirectory

### ISSUE THREAD

**Issue by codestation** [foxcpp/maddy#336]
# Describe the bug

Since the change to build.sh the maddy executable is built without setting `DefaultStateDirectory`. This means that the state is stored in `/var/lib/maddy` making it incompatible with the previous image (that uses `/data`) and documentation.

# Steps to reproduce

* Run `foxcpp/maddy:0.4.2` using the `/data` directory as volume per the documentation.
* Upgrade to `foxcpp/maddy:0.4.3`
* The previous dkim keys, users and mailboxes are ignored as they are no longer read from `/data`

# Environment information

* maddy version: 0.4.3

# Possible fix:

Restore statedir option in build.sh so it can use the custom location for the state.

**Comment by foxcpp** [comment]
https://lists.sr.ht/~foxcpp/maddy/%3Ca2c46637f6b6cb9f52618524e15da397%40disroot.org%3E

This mailing list post describes the configuration change needed. New containers have initial config already including these directives.
