### ISSUE TITLE
destination postmaster meaning in the config?

### ISSUE THREAD

**Issue by Defman21** [foxcpp/maddy#344]
In the default config, I have a bunch of `destination postmaster $(local_domains)` sections here and there. Is there something special about the `postmaster` argument or is it just a plain match like `$source contains any of (postmaster, some.domain, someother.domain)`? 

Thanks for your work, it was straightforward to spin up the server.

**Comment by foxcpp** [comment]
>or is it just a plain match like $source contains any of (postmaster, some.domain, someother.domain)

This.

Specifically, `postmaster` is a special address defined by RFC 5321, it does not have a domain part.
