### ISSUE TITLE
Add copyright notices in the license

### ISSUE THREAD

**Issue by gargakshit** [foxcpp/maddy#346]
https://github.com/foxcpp/maddy/blob/580a1718865b77c322fa7be1a8ed0e3c2136a2c6/COPYING#L634-L635

https://github.com/foxcpp/maddy/blob/580a1718865b77c322fa7be1a8ed0e3c2136a2c6/COPYING#L655

**Comment by foxcpp** [comment]
This text is part of the license. It is not supposed to be changed and just gives an example.

Corresponding copyright notices are added to all source code files:
https://github.com/foxcpp/maddy/blob/178579d78a93cd252f9af8ce4c5b56a8def1862d/internal/check/dkim/dkim_test.go#L2-L3

(probably should be patched up to be 2019-2021)
