### ISSUE TITLE
Docker container's expected certificate names, tls_cert.pem and tls_key.pem

### ISSUE THREAD

**Issue by Avamander** [foxcpp/maddy#350]
# Use case

Currently the docker container expects the certificates to be named `tls_cert.pem` and `tls_key.pem` but Certbot stores the two as `cert.pem` and `privkey.pem`. I guess reconfiguration is also possible, but why require that if it's possible not to.

# Your idea for a solution

It would just be really nice if reconfiguration could be avoided and the defaults allow very comfy and seamless mount+usage of Certbot's files.

- [ ] I'm willing to help with the implementation

**Comment by foxcpp** [comment]
So something like this
```
tls file /data/certs/$(hostname)/fullchain.pem /data/certs/$(hostname)/privkey.pem
```
is desired?
This could be achieved by changing TLS-related line in Dockerfile to:
```
RUN sed -Ei 's!/etc/maddy/certs!/data/certs!g' /pkg/data/maddy.conf
```

**Comment by Avamander** [comment]
> So something like this
> 
> ```
> tls file /data/certs/$(hostname)/fullchain.pem /data/certs/$(hostname)/privkey.pem
> ```
> 
> is desired?

Yep, something like that.

> This could be achieved by changing TLS-related line in Dockerfile to:
> 
> ```
> RUN sed -Ei 's!/etc/maddy/certs!/data/certs!g' /pkg/data/maddy.conf
> ```

I was more suggesting that if there isn't a reason to have the current names why not use the ones that don't require any renaming(/sed'ing).

**Comment by foxcpp** [comment]
There is a reason for putting configuration in /data* and then I just went with putting TLS keys there as well.

\* this locks configuration on first image use - exact config file contents are -not- covered by any compatibility promises.

**Comment by arisudesu** [comment]
I suggest to avoid sed-patching configuration in Dockerfile. It'd be better if the config embedded in the image was accessible in separate file in repo, rather than having to poke around in the image to extract it.

**Comment by foxcpp** [comment]
With the introduction of built-in ACME client, this issue is probably much less relevant. Howver, I will change default names to /data/tls/fullchain.pem, /data/tls/privkey.pem and put the maddy.conf used by Docker image in the repo.
