### ISSUE TITLE
I/O error while parsing header: smtp: too longer line in input stream

### ISSUE THREAD

**Issue by ntjy888** [foxcpp/maddy#352]
# Describe the bug

Can not get email from imap client.

# Steps to reproduce

open https://mp.weixin.qq.com/?lang=en_US&token=  and apply an account with email address to get verify code.

# Log files

```txt
smtp: RCPT ok	{"msg_id":"83ae4072","rcpt":"admin@*******.com"}
smtp: DATA error	{"msg_id":"83ae4072","reason":"I/O error while parsing header: smtp: too longer line in input stream"}
```

# Configuration file

default 

# Environment information

install from docker today.

**Comment by foxcpp** [comment]
maddy limits line length in SMTP stream to 2000 octets which is 2x of what RFC 5321 allows. QQ seems to generate non-conforming messages.

P.S. Postfix, a popular SMTP server implementation has even smaller limit set to 998 octets by default.
Hence I am hesitant to change the default limit. Would making it configurable be enough?

**Comment by ntjy888** [comment]
configurable will be great.

**Comment by foxcpp** [comment]
Added the corresponding configuration option in 66cb7170ab536e16787516a05acf2a59049c1946. Also doubled the default limit.

**Comment by foxcpp** [comment]
I assume the linked commit fixes the issue. Closing. Reopen if this is still relevant.
