### ISSUE TITLE
With tutorial config, the postmaster with no domain is not a valid recipient

### ISSUE THREAD

**Issue by arisudesu** [foxcpp/maddy#384]
# Describe the bug

With tutorial config, the postmaster with no domain is not a valid recipient.

I see that it was once described in the documentation as part of the config changes, but after several versions it is no longer in the config. As a result, it stopped working. 

Perhaps it was lost in commit 81e6a3b805c4bc9bc34eda27a7af579aded90a2b? Missing block (below) is what makes it work again.
```
replace_rcpt static {
    entry postmaster postmaster@$(primary_domain)
}
```

# Steps to reproduce

```$ telnet myhostname.dev 25
Trying xxx.xxx.xxx.xxx...
Connected to myhostname.dev.
Escape character is '^]'.

220 myhostname.dev ESMTP Service Ready

HELO myhostname.dev
250 2.0.0 Hello myhostname.dev

MAIL FROM: example@example.com
250 2.0.0 Roger, accepting mail from <example@example.com>

RCPT TO: postmaster
550 5.1.1 User doesn't exist (msg ID = 312f88ff)

^D
```

# Configuration file

[This](https://github.com/foxcpp/maddy/blob/v0.4.4/maddy.conf) with only difference in hostname.

# Environment information

* maddy version: 0.4.4

**Comment by foxcpp** [comment]
Resolved in the referenced commit. Pending for 0.5.1.

**Comment by arisudesu** [comment]
Thank you for the fix and this useful software.
