### ISSUE TITLE
Enforce DMARC policy

### ISSUE THREAD

**Issue by foxcpp** [foxcpp/maddy#39]
Before that, we need to get DKIM verification working.

- [x] Reject/mark incoming messages that violate DMARC policy of the source server
- [ ] Report generation

**Comment by emersion** [comment]
https://github.com/emersion/go-dmarc

**Comment by foxcpp** [comment]
Implemented basic authentication support, depends on https://github.com/emersion/go-msgauth/pull/11 so waiting for it.

**Comment by foxcpp** [comment]
Minimal alignment check implementation is in ad4c04452a9234adea18812c55fa78581fb56caf.

**Comment by foxcpp** [comment]
I think we can go without reports generation for 0.1, up for reconsideration later, though.
