### ISSUE TITLE
Add support for namecheap dns-01 challenge

### ISSUE THREAD

**Issue by ghost** [foxcpp/maddy#392]
# Use case

I noticed `dns-01` challenge for the ACME client was recently added in https://github.com/foxcpp/maddy/commit/93cf4f231a4e23ea7d6fef642024b027b39e995c, this issue (selfishly) suggests adding the namecheap dns provider.

# Your idea for a solution

There is already a module for [libdns namecheap](https://github.com/libdns/namecheap), so integration with maddy should be fairly straightforward. If this suggestion has support, I'd be happy to open a PR to add it.

- [x] I'm willing to help with the implementation

**Comment by foxcpp** [comment]
Just pushed c0845fb to master that adds namecheap provider.

**Comment by foxcpp** [comment]
Note to self: Using github.com/libdns/namecheap increased minimum Go version to 1.16 (before it was Go 1.14.3). Documentation, etc need updating.
