### ISSUE TITLE
maddy.service ExecStart changed to /usr/local/bin/maddy but documentation still says /usr/bin/maddy

### ISSUE THREAD

**Issue by voussoir** [foxcpp/maddy#407]
Hi, I want to start by saying I'm really enjoying Maddy! Thanks for your work.

In 06773552, the ExecStart line was changed to /usr/local/bin/maddy. This prevented my server from starting because I put the executables in /usr/bin according to [the tutorial](https://github.com/foxcpp/maddy/blob/3f1b6684aaebc91c99fd818e5ec3883eff019ae7/docs/tutorials/setting-up.md#installing-maddy) when I installed 0.50.

If anyone else finds that their server doesn't start after the 0.50 -> 0.51 transition, here is exactly what I was seeing. I'm just including this to help the search results maybe.

```
~> sudo systemctl start maddy

Job for maddy.service failed because the control process exited with error code.
See "systemctl status maddy.service" and "journalctl -xe" for details.
```

```
~> sudo systemctl status maddy

● maddy.service - maddy mail server
   Loaded: loaded (/etc/systemd/system/maddy.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2021-09-22 22:04:20 UTC; 4s ago
     Docs: man:maddy(1)
           man:maddy.conf(5)
           https://maddy.email
  Process: 686 ExecStart=/usr/local/bin/maddy (code=exited, status=203/EXEC)
 Main PID: 686 (code=exited, status=203/EXEC)

Sep 22 22:04:20 vps-67b55a0b systemd[1]: maddy.service: Service RestartSec=100ms expired, scheduling restart.
Sep 22 22:04:20 vps-67b55a0b systemd[1]: maddy.service: Scheduled restart job, restart counter is at 9.
Sep 22 22:04:20 vps-67b55a0b systemd[1]: Stopped maddy mail server.
Sep 22 22:04:20 vps-67b55a0b systemd[1]: maddy.service: Start request repeated too quickly.
Sep 22 22:04:20 vps-67b55a0b systemd[1]: maddy.service: Failed with result 'exit-code'.
Sep 22 22:04:20 vps-67b55a0b systemd[1]: Failed to start maddy mail server.
```

So I moved the executables to /usr/local/bin and everything is fine.

By the way, the same document says that tarball downloads are available via GitHub releases or on the maddy.email website, but I don't see any downloads page on the website. This information may be out of date as well.

Thanks!

**Comment by foxcpp** [comment]
The link in documentation is slightly wrong. It should lead to https://maddy.email/builds/

**Comment by foxcpp** [comment]
Referenced commit fixes the link in the tutorial. Closing the issue as it is non-actionable.
