### ISSUE TITLE
DMARC policy message always prints

### ISSUE THREAD

**Issue by Nairou** [foxcpp/maddy#408]
I noticed I was getting the following message for every incoming email: `check.spf: deferring action due to a DMARC policy`

I did a code search, and it appears that the same message is printed regardless of the outcome of the spf check:
https://github.com/foxcpp/maddy/blob/3f1b6684aaebc91c99fd818e5ec3883eff019ae7/internal/check/spf/spf.go#L392

**Comment by foxcpp** [comment]
IIRC res.err is always non-nil so it is kind of a bug here.
