### ISSUE TITLE
Automatic alias creation

### ISSUE THREAD

**Issue by Nairou** [foxcpp/maddy#412]
# Use case

I'm trying to move towards a system of having a different email alias for each service/mailinglist/etc. Right now that requires that I first SSH into my server, add the new alias, possibly restart maddy (not sure if required), and only then continue the signup of whatever service I wanted to use the email alias for. It would be nice if this process could be automated.

# Your idea for a solution

It would be nice if there was a setting to allow maddy to automatically create an alias, pointing to a configured primary email address, whenever it received email for a valid domain for which no alias already existed.

So, for example, if my real mailbox is nairou@mydomain.com and I sign up for netflix and give them netflix@mydomain.com, then:

1. maddy would see the incoming signup email, note that mydomain.com is valid but no alias for netflix@mydomain.com exists
2. automatically add the alias to `/etc/maddy/aliases`
3. immediately forward the email to nairou@mydomain.com as if the alias already existed

I don't know if maddy currently supports the ability to disable aliases (documentation on aliases is lacking), but that may be required as well, so spam mail going to an unused alias could be explicitly rejected, for example:

`unused@mydomain.com: reject`

Right now, the lack of a manually created alias gives this same result, but you don't want to delete an alias and have it automatically recreated when what you really want is to reject those emails.

- [ ] I'm willing to help with the implementation
(I am not familiar enough with the maddy codebase to know where to start on helping with this)

**Comment by foxcpp** [comment]
You can implement this using address rewriting facilities already available in maddy, as described in more detail in https://github.com/foxcpp/maddy/issues/243#issuecomment-655694512.

Here is the configuration snippet that probably belongs somewhere in `local_routing` part of default config.
```
# If there exists an explicitly created mailbox with that name - send it there.
destination_in &local_mailboxes {
    deliver_to &local_mailboxes
}
# If that's a disabled address - reject the message.
destination_in file /etc/maddy/disabled-aliases { 
    reject
}
# Otherwise, send it to catchall@example.org
destination example.org {
    modify {
        replace_rcpt regexp ".*" "catchall@example.org"
    }
    deliver_to &local_mailboxes
}
```

**Comment by Nairou** [comment]
@foxcpp Thanks! That looks very promising.

This is what I currently have for `local_routing`, I'm guessing your snippet would replace it entirely?

```
msgpipeline local_routing {
    # Insert handling for special-purpose local domains here.
    # e.g.
    # destination lists.example.org {
    #     deliver_to lmtp tcp://127.0.0.1:8024
    # }

    destination postmaster $(local_domains) {
        modify {
            replace_rcpt &local_rewrites
        }

        deliver_to &local_mailboxes
    }

    default_destination {
        reject 550 5.1.1 "User doesn't exist"
    }
}
```

I'm not sure what the difference is between your `destination ...` example, and the `destination postmaster ...` version I currently have by default.

**Comment by foxcpp** [comment]
>I'm not sure what the difference is between your destination ... example, and the destination postmaster ... version I currently have by default.

The difference use of `local_rewrties` block (which includes /etc/maddy/aliases processing) and `local_domains` placeholder instead of example.org.

Full block would look something like this:
```
msgpipeline local_routing {
    modify {
        # Apply local rewrites (/etc/maddy/aliases, plus-addressing, etc).
        replace_rcpt &local_rewrites
    }

    # If there exists an explicitly created mailbox with that name - send it there.
    destination_in &local_mailboxes {
        deliver_to &local_mailboxes
    }
    # If that's a disabled address - reject the message.
    destination_in file /etc/maddy/disabled-aliases { 
        reject
    }
    # Otherwise, if it is a domain we want to handle (as specified by local_domains) 
    # or special-purpose <postmaster> address - send it to catchall@example.org account.
    destination postmaster $(local_domains) {
        modify {
            replace_rcpt regexp ".*" "catchall@example.org"
        }
        deliver_to &local_mailboxes
    }

    # And in the end. If it is neither - reject it as unknown.
    default_destination {
        reject 550 5.1.1 "User doesn't exist"
    }
}
```

**Comment by Nairou** [comment]
Thank you, that appears to work great!
