### ISSUE TITLE
Allow send email aliases for any managed domain

### ISSUE THREAD

**Issue by Nairou** [foxcpp/maddy#419]
# Use case

I use a catch-all for receiving emails from multiple domains to a single mailbox. On rare occasion, I need to respond to one of these emails, but doing so would expose my real email address. Attempting to change the "from" address results in an unauthorized error if it isn't a previously-created credential. For now, I have to manually create a new credential for the specific email address, in order to send an email with that address. It would be nice if this wasn't necessary.

# Your idea for a solution

It would be nice if there was a config setting to allow sending of emails with a "from" address of (anything)@domain.com, assuming it is a domain that is in the config. Essentially, a "catch-all" for sending.

Another (less automatic) idea would be to have another aliases file, but for sending, so I can map a fake address to a real address, and be allowed to send emails from that fake address.

**Comment by foxcpp** [comment]
Sender address authorization in default configuration transforms the used sender address using same mapping that is used for aliases.

```
table.chain local_rewrites {
    optional_step regexp "(.+)\+(.+)@(.+)" "$1@$3"
    optional_step static {
        entry postmaster postmaster@$(primary_domain)
    }
    optional_step file /etc/maddy/aliases
}
```

```
...
   source $(local_domains) {
        check {
            authorize_sender {
                prepare_email &local_rewrites # <----
                user_to_email identity  # email == username
            }
        }

        destination postmaster $(local_domains) {
            deliver_to &local_routing
        }
        default_destination {
            modify {
                dkim $(primary_domain) $(local_domains) default
            }
            deliver_to &remote_queue
        }
...
```

```
 replace_rcpt regexp ".*" "catchall@example.org"
```
If you do something like this for catch-all and put it into `local_rewrites` then it should just work.

**Comment by Nairou** [comment]
Belated thanks! I haven't had the chance to test this out but your example makes sense. I'll go ahead and close this issue for now.
