### ISSUE TITLE
Docker container errors on startup "maddy.conf: no such file or directory"

### ISSUE THREAD

**Issue by heathlarsen** [foxcpp/maddy#445]
I'm trying to spin up Maddy in Docker on my Synology NAS via command line.
```
docker run \
   --name maddy \
   -e MADDY_HOSTNAME=mail.<redacted>.net \
   -e MADDY_DOMAIN=<redacted>.net \
   -v /volume7/docker/maddy/data:/data \
   -p 25:25 \
   -p 143:143 \
   -p 465:465 \
   -p 587:587 \
   -p 993:993 \
   foxcpp/maddy:latest
```

This command immediately returns an error and the container crashes:
`open /data/maddy.conf: no such file or directory`

The directory _**/volume7/docker/maddy/data**_ definitely exists on the host machine but no files get created there.

**Comment by foxcpp** [comment]
I suppose it would work correctly and write its configuration only when Docker volume is used (`docker volume create ...`, `-v volumename:/data`.

**Comment by heathlarsen** [comment]
You're totally right!
I ran `docker volume create temp` and updated my docker run command to use `-v temp:/data`.
The maddy.conf was generated, the error didn't reoccur and this allowed me to progress to the TLS cert step.

Because I prefer to use specific directories in the host filesystem for my volumes I moved the newly generated maddy.conf out of the temp volume and into my preferred directory (`/volume7/docker/maddy/data`).
I then deleted the docker container and spun it back up up with the original `-v /volume7/docker/maddy/data:/data` volume flag. It seems to be happy with that. 👍 

Thank you for your help!

**Comment by pointful** [comment]
It would be nice to get the Maddy container updated to support the pattern of creating maddy.conf when the volume is mapped to an explicit directory since that's a pretty common practice for a lot of docker users and containers. Ran into this same issue and had to dig through Github issues to find this as the cause fo the problem.
