### ISSUE TITLE
IMAP IDLE capability missing (Push support)

### ISSUE THREAD

**Issue by Dr-Escher** [foxcpp/maddy#446]
# Describe the bug

Latest maddy doesn't report the IMAP IDLE capability, rendering message pushing unavailable.

# Steps to reproduce

- Deploy maddy v0.5.2 (foxcpp/maddy@3ae07046c11ee3eba162a2b1a8a82e054a8227e4)
- Connect via IMAP (thunderbird 91.5.0-0.1 via `export MOZ_LOG=IMAP:4` in this case)
- Observe reported IMAP capabilities

# Log files

0. maddy instance
[Parent 11216: IMAP]: I/IMAP 7f63b185f800:redacted:NA:CreateNewLineFromSocket: 45 OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR CHILDREN UNSELECT MOVE APPENDLIMIT APPENDLIMIT CHILDREN I18NLEVEL=1 SORT THREAD=ORDEREDSUBJECT COMPRESS NAMESPACE] AUTHENTICATE completed

Other examples for reference:
1. generic provider A
[Parent 11216: IMAP]: I/IMAP 7f63bdbea000:redacted:NA:CreateNewLineFromSocket: 93 OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE **IDLE** SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SPECIAL-USE QUOTA] Logged in

2. generic provider B
[Parent 11216: IMAP]: I/IMAP 7f63b1877000:redacted:A:CreateNewLineFromSocket: * CAPABILITY IMAP4rev1 CHILDREN ENABLE ID **IDLE** LIST-EXTENDED LIST-STATUS LITERAL- MOVE NAMESPACE SASL-IR SORT SPECIAL-USE THREAD=ORDEREDSUBJECT UIDPLUS UNSELECT WITHIN APPENDLIMIT=29360128

3. generic provider C
[Parent 11216: IMAP]: I/IMAP 7f63b1869800:redacted:NA:CreateNewLineFromSocket: 61 OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE **IDLE** SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY PREVIEW=FUZZY XLIST LITERAL+ NOTIFY SPECIAL-USE] Logged in

# Configuration file

Default configuration except `$(hostname)` and `$(primary_domain)`
https://github.com/foxcpp/maddy/blob/59727496a949a38ba6d8a9ab1d3aacc086689165/maddy.conf#L1

# Environment information

* maddy 0.5.2 on Debian 11.2
* https://maddy.email/specifications/#extensions

**Comment by foxcpp** [comment]
That seems to be the regression in go-imap 1.2.
Ref. https://github.com/emersion/go-imap/pull/453

**Comment by Dr-Escher** [comment]
Confirmed to be fixed in go-imap v1.2.1
