### ISSUE TITLE
can sync mail from gmail to maddy via imapsync

### ISSUE THREAD

**Issue by vtolstov** [foxcpp/maddy#470]
```
Err 20/50: - msg &BC8EPQQ0BDUEOgRB-/24310 {35630523} could not append ( Subject:[=?UTF-8?B?0JXQu9C60LAgNQ==?=], Date:["12-Jan-2018 17:37:32 +0000"], Size:[35630523], Flags:[\Seen] ) to folder &BC8EPQQ0BDUEOgRB-: 6960 NO [TOOBIG] Message size exceeding limit
```

How to increase message size limit in maddy?

**Comment by foxcpp** [comment]
Size of messages written via IMAP is limited via `appendlimit` directive for the [storage.imapsql module](https://github.com/foxcpp/maddy/blob/dev/docs/reference/storage/imapsql.md). Default is 32 MiB. Message that caused the error is almost 33.9 MiB.

To double the limit:
```
storage.imapsql local_mailboxes {
  ...
  appendlimit 64M
}
```
