### ISSUE TITLE
Enforce DANE policy

### ISSUE THREAD

**Issue by foxcpp** [foxcpp/maddy#50]
It would be nice to support DANE in addition to MTA-STS to increase interoperability.

Again, there are two sides in DANE support:
- Check DANE for remote MTAs
- ~~Check if we have DANE record and reject unencrypted MTA connections.~~

https://tools.ietf.org/html/rfc7672

**Comment by emersion** [comment]
DANE requires DNSSEC right?

**Comment by foxcpp** [comment]
Yep.

**Comment by foxcpp** [comment]
Perhaps we should include a small DNSSEC-enabled resolver in maddy. This will also make things slightly more secure in general.

**Comment by emersion** [comment]
I wonder how this could integrate with the Go standard library. Is there a way to override the resolver?

**Comment by foxcpp** [comment]
It doesn't seem to be possible, sadly.

**Comment by emersion** [comment]
https://github.com/golang/go/issues/13279

**Comment by foxcpp** [comment]
I would count this as a low-priority issue, after some research I found out that DANE is much less widely deployed then MTA-STS (to the point where it took a lot of effort to find ONE domain with a TLSA record).
