### ISSUE TITLE
IMAP IDLE is missing from server-reported capabilities again

### ISSUE THREAD

**Issue by Dr-Escher** [foxcpp/maddy#504]
Not sure if this is the exact same issue as https://github.com/foxcpp/maddy/issues/446 (which got fixed), however [v0.6.0](https://github.com/foxcpp/maddy/releases/tag/v0.6.0) shows similar behaviour again.

# Describe the bug

Latest maddy doesn't report the IMAP IDLE capability, rendering message pushing unavailable.

# Steps to reproduce

Connect to maddy v0.6.0 https://github.com/foxcpp/maddy/commit/840d68779e79fe45bfeb5d3bc0e83d6573834c22 via IMAP

# Log files

`[Parent 2668: IMAP]: I/IMAP 7f257a1af800:NA:CreateNewLineFromSocket: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR CHILDREN UNSELECT MOVE APPENDLIMIT AUTH=PLAIN AUTH=LOGIN COMPRESS] IMAP4rev1 Service Ready`

# Configuration file

Default configuration

# Environment information

* maddy version: v0.6.0
* Debian version: 11.3

**Comment by foxcpp** [comment]
You are right, this is exactly the same issue - go-imap v2 apparently was never updated to include fix that was made for v1 (version used by maddy 0.5).

**Comment by foxcpp** [comment]
Should be fixed in 0.6.1. Thanks for letting me know.

**Comment by Dr-Escher** [comment]
Yes, I can confirm this is fixed in v0.6.1 https://github.com/foxcpp/maddy/commit/bbaea0400e5c89835ca6d04f0f84c036e9a3922a

Awesome, thank you.
