### ISSUE TITLE
Arch linux 3rd party repository seems down

### ISSUE THREAD

**Issue by mfashby-tailscale** [foxcpp/maddy#513]
# Describe the bug

Installation instructions for arch linux point to a custom repository https://foxcpp.dev/archlinux/

Unfortunately this URL is redirecting me here https://ww01.foxcpp.dev/?pid=9POT3387I&pbsubid=cadb44b3-07c2-c0e6-142f-6c5003500be6&noads=http%3A%2F%2Fww01.foxcpp.dev%2F%3Fskipskenzo%3Dtrue

And I promptly get a certificate error, as the cert is issued to 'testexp'

# Steps to reproduce

as description

# Log files

n/a

# Configuration file

n/a

# Environment information

n/a

**Comment by foxcpp** [comment]
Arch Linux repository was dead for good for a while. I will get it back together during this weekend.

**Comment by MFAshby** [comment]
Thanks, this looks fixed, at least links from documentation take you to a working site :)

**Comment by foxcpp** [comment]
Repository is back and updated with latest maddy release.
