### ISSUE TITLE
No maddyctl in tar.zst file

### ISSUE THREAD

**Issue by pouriya** [foxcpp/maddy#543]
Hi. The [documentation](https://maddy.email/tutorials/setting-up/#installing-maddy) says that there should be an executable `maddyctl` inside tarball but it seems that there is no such file there.

# Log files
```sh
$ tar --use-compress-program=unzstd -xvf maddy-0.6.2-x86_64-linux-musl.tar.zst 
./maddy-0.6.2-x86_64-linux-musl/
./maddy-0.6.2-x86_64-linux-musl/maddy.conf
./maddy-0.6.2-x86_64-linux-musl/systemd/
./maddy-0.6.2-x86_64-linux-musl/systemd/maddy@.service
./maddy-0.6.2-x86_64-linux-musl/systemd/maddy.service
./maddy-0.6.2-x86_64-linux-musl/maddy
```

* maddy version: 0.6.2

**Comment by foxcpp** [comment]
Woops, another maddyctl mention I forgot to update. Since 0.6, maddyctl is part of maddy executable. e.g. `maddyctl whatever` is `maddy whatever`.

**Comment by pouriya** [comment]
Hmmmmm. I happens dude. I just opened #545
