### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by xdkaka** [foxcpp/maddy#550]
# Use case

What problem you are trying to solve?
I want to install multiple SMTP services in different IPs. When one ip fails to send emails, it will automatically switch to another server to send emails.

# Your idea for a solution

How your solution would work in general?
I can set ``target.smtp outbound_delivery `` multiple targets?
how should I do？Thank you

- [ ] I'm willing to help with the implementation

**Comment by foxcpp** [comment]
https://maddy.email/reference/targets/smtp/
>Syntax: targets endpoints...
>Default: not specified
>
>REQUIRED.
>
>List of remote server addresses to use. See [Address definitions](https://maddy.email/reference/config-syntax/#address->definitions) for syntax to use. Basically, it is 'tcp://ADDRESS:PORT' for plain SMTP and 'tls://ADDRESS:PORT' for >SMTPS (aka SMTP with Implicit TLS).
>
>**Multiple addresses can be specified, they will be tried in order until connection to one succeeds (including TLS handshake if TLS is required).**

**Comment by xdkaka** [comment]
> https://maddy.email/reference/targets/smtp/
> 
> > Syntax: targets endpoints...
> > Default: not specified
> > REQUIRED.
> > List of remote server addresses to use. See [Address definitions](https://maddy.email/reference/config-syntax/#address-%3Edefinitions) for syntax to use. Basically, it is 'tcp://ADDRESS:PORT' for plain SMTP and 'tls://ADDRESS:PORT' for >SMTPS (aka SMTP with Implicit TLS).
> > **Multiple addresses can be specified, they will be tried in order until connection to one succeeds (including TLS handshake if TLS is required).**

Thank you

**Comment by imzykk** [comment]
> https://maddy.email/reference/targets/smtp/
> 
> > Syntax: targets endpoints...
> > Default: not specified
> > REQUIRED.
> > List of remote server addresses to use. See [Address definitions](https://maddy.email/reference/config-syntax/#address-%3Edefinitions) for syntax to use. Basically, it is 'tcp://ADDRESS:PORT' for plain SMTP and 'tls://ADDRESS:PORT' for >SMTPS (aka SMTP with Implicit TLS).
> > **Multiple addresses can be specified, they will be tried in order until connection to one succeeds (including TLS handshake if TLS is required).**

I have tried,only when the connection fails,and another server will be retried.
But if a server fails to send(For example, the server IP address can't connect receiver or IP addressis blocked), it will not switch to another server to send.
What should I do to make it work? Thank you
