### ISSUE TITLE
How to realize the function of mail group?

### ISSUE THREAD

**Issue by imzykk** [foxcpp/maddy#558]
# Use case

What problem you are trying to solve?
I want to realize the function of mail group, for example, all-staff@mail.com, hr@mail.com, When these group emails receive emails, people in the group can also receive emails,how can i do it

# Your idea for a solution
via alias? Copy the email content to everyone's ``Maildir``. If there are many people, it will take a long time and take up large resources.
Is there a better way? Thank you

- [ ] I'm willing to help with the implementation

**Comment by foxcpp** [comment]
Since 0.6 it is possible to specify multiple recipients in alias expansion.

Example using table.regexp:
```
replace_rcpt regexp "root@(.+)" "admin1@$1" "admin2@$1"
```

In table.file format (e.g. /etc/maddy/aliases in default config)
```
root@example.com: admin1@example.com, admin2@example.com
```

**Comment by imzykk** [comment]
> Since 0.6 it is possible to specify multiple recipients in alias expansion.
> 
> Example using table.regexp:
> 
> ```
> replace_rcpt regexp "root@(.+)" "admin1@$1" "admin2@$1"
> ```
> 
> In table.file format (e.g. /etc/maddy/aliases in default config)
> 
> ```
> root@example.com: admin1@example.com, admin2@example.com
> ```

Thank you for replay, I now alias, but the message content will be stored in multiple copies, Is it possible to store only one ?

**Comment by foxcpp** [comment]
>Is it possible to store only one ?

currently not, storage.imapsql does not deduplicate content in any way

**Comment by foxcpp** [comment]
Closing as answered. If you have further questions - feel free to reopen or create a new issue.
