### ISSUE TITLE
Does maddy support tcp6/ipv6 listen on ipv6 port?

### ISSUE THREAD

**Issue by mateors** [foxcpp/maddy#562]
Can I run maddy email server listening on the ipv6 port?
I tried but failed so does anyone knows if it is possible and how.

**Comment by foxcpp** [comment]
`tcp://0.0.0.0:587` and `tcp://[::]:587` will listen on both IPv4 and IPv6. You can specify an IPv6 address to listen only on IPv6: `tcp://[2607:5300:60:126b::1]:587`. No need to qualify `tcp` as `tcp4` or `tcp6`.

**Comment by mateors** [comment]
@foxcpp 
**tcp://[::]:25** I updated this, seems maddy running without issue but the port is unable to communicate, it says ...
```Result: FAILED: dial tcp [fe80::216:3cff:fec9:7f0f]:25: connect: invalid argument```

> `nano /etc/maddy/maddy.conf`
![image](https://user-images.githubusercontent.com/17635146/210855205-7d83dd8b-d50b-4f0e-89a6-f8c5bc432fe5.png)

![image](https://user-images.githubusercontent.com/17635146/210855271-25a1f22d-0207-424a-9038-45e1984f1cc5.png)

**Comment by foxcpp** [comment]
You did set an IPv6 [link-local address](https://en.wikipedia.org/wiki/Link-local_address) as an AAAA record. These addresses are not meaningful outside of your (or providers) network and won't work.

**Comment by mateors** [comment]
@foxcpp Actually I wanted to establish a similar connection as you see in the below screenshot
![image](https://user-images.githubusercontent.com/17635146/210914375-feed6c10-c276-46a3-ac79-097f97b690ca.png)

so as you mentioned my IPV6 is valid for local networking only, this is not a public ipv6, and for the above connection, I need to have a public IPV6 right?

**Comment by mateors** [comment]
I removed the **AAAA** record from my **DNS Zone** and it seems working!

![image](https://user-images.githubusercontent.com/17635146/210916885-92cab5ae-b222-49e9-bd29-e1f8c8576867.png)

**Comment by foxcpp** [comment]
Yup, you are right.
