### ISSUE TITLE
maddy.email has broken DNSSEC

### ISSUE THREAD

**Issue by vojta001** [foxcpp/maddy#563]
# Describe the bug

I can't open [maddy.email](https://maddy.email) in environments that strictly validate DNSSEC. Both [DNSViz](https://dnsviz.net/d/maddy.email/dnssec/) and [Zonemaster](https://zonemaster.labs.nic.cz/result/82fced228a985474) show problems as well as resolving it via [Google's DNS](https://dns.google/query?name=maddy.email&rr_type=A&ecs=&show_dnssec=true).

**Comment by Showfom** [comment]
Same here.

**Comment by foxcpp** [comment]
I am aware of the issue. I recently transfered maddy.email to a different registrar. The new one does not support DNSSEC for .email for some reason but DS record from the old registrar was preserved. I cannot change DS record via new regitrar's panel so I contacted the tech support. They told they will remove the broken record. Still waiting for them to do that.

**Comment by foxcpp** [comment]
I uploaded the website to GitHub Pages in meanwhile: https://foxcpp.github.io/maddy/
Release builds are available on GitHub as well: https://github.com/foxcpp/maddy/releases

**Comment by foxcpp** [comment]
maddy.email is back with properly configured DNSSEC. If it still does not load for some people - it's just DNS caching.

**Comment by vojta001** [comment]
I can confirms it's fixed. Thanks
