### ISSUE TITLE
Message-ID RHS is not a fully-qualified domain name

### ISSUE THREAD

**Issue by AlphaJack** [foxcpp/maddy#564]
# Describe the bug

The Message-ID in my case uses the pod name rather than the FQDN specified as MADDY_HOSTNAME.

Outgoing email are added a +0.50 SPAM score from Rspamd because of this reason (MID_RHS_NOT_FQDN)

Current: CPUZO502K586.2R999YBYXPTR5@mail
Ideal: CPUZO502K586.2R999YBYXPTR5@example.org

**Comment by foxcpp** [comment]
This message does not look like one generated by maddy. It is likely set by the client.

**Comment by AlphaJack** [comment]
You are right, sending from the Gmail android app generates XXXXXX@email.android.com
