### ISSUE TITLE
prepare_email is not documented, user_to_email is poorly described

### ISSUE THREAD

**Issue by arisudesu** [foxcpp/maddy#565]
# Describe the bug

`prepare_email` is missing explanation in reference, as well as `user_to_email` has poor description as "lookup table" (from what to what?).

It is only possible to deduce from code what it does: `prepare_email` takes e-mail address from "From" (1) field and maps it to single address or list of some addresses (A). Then authentication e-mail is mapped to list of addresses or domains (B) by `user_to_email`, and then if any address (or domain) from (A) belongs in (B) user is considered to be allowed sending from (1).

**Comment by foxcpp** [comment]
Documentation is improved in [6453363](https://github.com/foxcpp/maddy/commit/6453363eb58f86d75bbcc7601572e3cb8674800e) .
