### ISSUE TITLE
auth_map: unknown module or global directive

### ISSUE THREAD

**Issue by pkejval** [foxcpp/maddy#586]
Following docs https://github.com/foxcpp/maddy/blob/master/docs/multiple-domains.md 
I put directive `auth_map email_localpart_optional # authenticating as "user@*" checks credentials for "user"`
right under `$(local_domains) = $(primary_domain)` but getting this warning in logs `/data/maddy.conf:15: unknown module or global directive: auth_map`

Am I doing something wrong or docs are not up-to-date with code?

**Comment by jennydaman** [comment]
Please upgrade to version 0.7.0

**Comment by foxcpp** [comment]
Updated `auth_map` directive is part of 0.7.0.
