### ISSUE TITLE
Link to DNS configuration on Docker tutorial page is broken

### ISSUE THREAD

**Issue by rdbell** [foxcpp/maddy#590]
# Describe the bug

Link to DNS configuration on Docker tutorial page is broken

# Steps to reproduce

- Visit [https://maddy.email/docker/](https://maddy.email/docker/)
- Click the '[tutorials/setting-up/](https://maddy.email/docker/tutorials/setting-up/)' link at the end of the article.
- 404

# Log files

N/A

# Configuration file

N/A

# Environment information

N/A

* maddy version: N/A

**Comment by cuu508** [comment]
Looks like this was fixed in https://github.com/foxcpp/maddy/commit/b3980ff715a430dda59fff3b84a40e25b8dfa01b
