### ISSUE TITLE
Fail check with go test or test/run.sh

### ISSUE THREAD

**Issue by mek-yt** [foxcpp/maddy#618]
# Describe the bug

I can't install maddy from AUR since version 0.7.0 without locally removing `check()` from the PKGBUILD. 

# Steps to reproduce

```sh
git clone https://github.com/foxcpp/maddy
cd maddy
go test ./...
# Fail
cd tests
./run.sh
# Fail
```

# Log files

Output of `go test ./...` in file [test_run.log](https://github.com/foxcpp/maddy/files/12370225/test_run.log).
Output of `./run.sh` in file [test_go.log](https://github.com/foxcpp/maddy/files/12370226/test_go.log).

# Environment information

* maddy version: 37bbd40189562aa2bae9bc640c2c013e6842a3a2 or [v0.7.0](https://github.com/foxcpp/maddy/releases/tag/v0.7.0)

**Comment by foxcpp** [comment]
Possibly related: 8834501

**Comment by mek-yt** [comment]
I test on d9920f0763cdaf6e49d015732b0de499299fbace and both test succeed, thanks :smile:
