### ISSUE TITLE
Bug report: ssl cert expired for docs site

### ISSUE THREAD

**Issue by gedw99** [foxcpp/maddy#659]
# Describe the bug

What do you think is wrong?

<img width="1728" alt="Screenshot 2023-12-21 at 12 22 56" src="https://github.com/foxcpp/maddy/assets/53147028/db9235da-4aef-4163-bd18-c11b7135f59a">

**Comment by hugmouse** [comment]
Seems ok from on my side. Maybe force refresh the page?

<img width="537" alt="Screenshot 2023-12-21 at 13 39 27" src="https://github.com/foxcpp/maddy/assets/44648612/d6796ab5-9e1c-4a1b-987b-feaa5c2e2d49">

**Comment by foxcpp** [comment]
No problems on my end either. Could you click "view the certificate" and show what the received certificate is?

**Comment by gedw99** [comment]
can do...

Just need work out with safari how to get ALL the Cert info out of the thing....

**Comment by gedw99** [comment]
In chrome its fine..

I got a Mac OS upgrade today so will let that run and then see...

**Comment by hugmouse** [comment]
Seems to be ok on Safari too

![Uploading Screenshot 2023-12-21 at 16.31.11.png…]()

**Comment by gedw99** [comment]
yep its fine now that I did an OS update. Must have been the OS level chain of trust on the certs.

will close this @foxcpp 

false alarm :)
