### ISSUE TITLE
Unable to start Ubuntu 22.04.3 LTS aarch64

### ISSUE THREAD

**Issue by mateors** [foxcpp/maddy#666]
# Unable to run at Ubuntu 22.04 LTS arm64 

I installed it using building from source https://maddy.email/tutorials/building-from-source/

PLEASE HELP ME ASAP.

What do you think is wrong?
unknown driver "sqlite3" (forgotten import?)

# Log files
```
Jan 14 08:08:11 shaperk maddy[401183]: imapsql: NewBackend (open): sql: unknown driver "sqlite3" (forgotten import?)
Jan 14 08:08:11 shaperk systemd[1]: maddy.service: Main process exited, code=exited, status=1/FAILURE
Jan 14 08:08:11 shaperk systemd[1]: maddy.service: Failed with result 'exit-code'.
Jan 14 08:08:11 shaperk systemd[1]: Failed to start maddy mail server.
Jan 14 08:08:11 shaperk systemd[1]: maddy.service: Scheduled restart job, restart counter is at 5.
Jan 14 08:08:11 shaperk systemd[1]: Stopped maddy mail server.
Jan 14 08:08:11 shaperk systemd[1]: maddy.service: Start request repeated too quickly.
Jan 14 08:08:11 shaperk systemd[1]: maddy.service: Failed with result 'exit-code'.
Jan 14 08:08:11 shaperk systemd[1]: Failed to start maddy mail server.
Jan 14 08:08:18 shaperk pdns_server[75291]: WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
```

* maddy version: ?
```
0.7.0+de756c8 linux/arm64 go1.21.6

default config: /etc/maddy/maddy.conf
default state_dir: /var/lib/maddy
default runtime_dir: /run/maddy
```

**Comment by foxcpp** [comment]
Did you have gcc installed when compiling maddy? It is required for sqlite3 support to work.

**Comment by mateors** [comment]
@foxcpp should I try again with the latest push you made?

**Comment by foxcpp** [comment]
Yes, you can try. I added an alternative solution for the problem.

**Comment by mateors** [comment]
@foxcpp is there any way I can read mail using pop3?  I want to read mail from gmail, but seems gmail only support pop3, I appreciate your suggestion on this.

**Comment by foxcpp** [comment]
No, unfortunately maddy currently does not support POP3. See #650.

**Comment by mateors** [comment]
@foxcpp okay, got it. any plan in future?

**Comment by foxcpp** [comment]
>@foxcpp okay, got it. any plan in future?

Definitely, it has been requested several times already.  Can't give any specific timeline though.

**Comment by foxcpp** [comment]
Feel free to reopen if you are still unable to get maddy to run, POP3 support is to be discussed in #650.
