### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by dazrik** [foxcpp/maddy#696]
Looks like the [maddy.email](https://maddy.email) website is down.

Any information about this?

**Comment by hugmouse** [comment]
Maddy.email uses Timeweb for hosting and it's currently down. So just wait for some time :)

In the meantime, you can use the docs available in the repo: https://github.com/foxcpp/maddy/tree/master/docs

**Comment by dazrik** [comment]
Thanks @hugmouse, I wasn't aware that the documentation is still available on GitHub as the wiki page of the repo says that it has been moved.

Anyway, the website seems to be back online now so I'm closing this issue :)
