### ISSUE TITLE
PostgreSQL peer auth doesn't work

### ISSUE THREAD

**Issue by lilydjwg** [foxcpp/maddy#725]
# Describe the bug

I'm using PostgreSQL with peer auth, i.e. the UNIX user maddy connects to PostgreSQL locally with the PostgreSQL user without a password.

I'd like to not use a password so that I don't need to manage it and keep it safe.

# Steps to reproduce

It doesn't start.

# Log files

```
imapsql: NewBackend (schemaVersion): pq: password authentication failed for user "maddy"
```

# Configuration file
```
storage.imapsql local_mailboxes {                                                                                                                                                          
    driver postgres                                                                                                                                                                        
    dsn "user=maddy dbname=maddy sslmode=disable"                                                                                                                                          
}                                                                                                                                                                                          
```

# Environment information

* maddy version: 0.7.1

**Comment by foxcpp** [comment]
Try specifying unix socket path explicitly e.g. `host=/tmp/postgres`

Relevant PostgreSQL driver issue: https://github.com/lib/pq/issues/645

**Comment by lilydjwg** [comment]
It works, thanks! My search didn't hit that issue.
