### ISSUE TITLE
Figure out how to interact with DNS and HTTPS

### ISSUE THREAD

**Issue by emersion** [foxcpp/maddy#8]
Things like DKIM, MTA-STS are tightly coupled with DNS and HTTPS.

Should we become tiny DNS/HTTPS servers too?

**Comment by foxcpp** [comment]
I don't like the idea of having an embedded DNS server. That's too much for maddy IMO, DNS is hard to get right.
For DKIM, we can generate keypair and zone file with public key (somewhere in /var/maddy/, perhaps) so it can be included from user's main zone file.

**Comment by emersion** [comment]
Yeah, that's probably a better idea.

**Comment by emersion** [comment]
That still leaves the question of HTTPS: where do we get certs from?

It would be nice to be able to have automatic HTTPS. Maybe we can use https://github.com/mholt/certmagic (maybe it requires having an HTTP server)

MTA-STS involves serving an HTTPS document btw.

**Comment by foxcpp** [comment]
Well, I guess we can then start net/http server and bind on 127.0.0.1:some_probably_unused_port to serve just this file. Note that it is important to be able to change the port or fully disable this feature.

**Comment by emersion** [comment]
MTA-STS requires port 443. And I think it's the same for ACME challenges…

**Comment by foxcpp** [comment]
Leave the job of HTTPS to reverse proxy then? I never liked this automagic with TLS, right now it just increases complexity by restricting use-cases (separate domain for mail) and requiring more actions to be taken to work in existing environments (clashes with caddy and manual TLS configuration).

**Comment by foxcpp** [comment]
Issue #67 had some discussion related to the HTTP endpoint module starting at https://github.com/emersion/maddy/issues/67#issuecomment-491936697. I guess we are going with approach outlined in https://github.com/emersion/maddy/issues/67#issuecomment-493765888.

**Comment by MFAshby** [comment]
Just FYI caddy server has some code for interacting with a variety of DNS providers' APIs, so that it can automatically create DNS entries: https://github.com/caddyserver/dnsproviders

**Comment by foxcpp** [comment]
Closing as a too broad ticket. ACME TLS autoconfiguration is discussed in #3, considerations for static webserver for autoconfiguration and other purposes are mentioned in #67 and idea with builtin DNS server is discarded as not useful enough for its complexity.
