### ISSUE TITLE
Authentication attempts throttling

### ISSUE THREAD

**Issue by foxcpp** [foxcpp/maddy#88]
I wonder whether we need something built in or just document how to set up fail2ban for it.

**Comment by emersion** [comment]
Yeah, I'm not sure. Throttling per-account is dangerous because it can lead to per-account DOS.

**Comment by foxcpp** [comment]
Per-IP throttling then?

**Comment by emersion** [comment]
Yup, but that's something fail2ban can do without our help.

**Comment by foxcpp** [comment]
Then we should ship fail2ban configuration with maddy, especially since foxcpp/go-imap-sql#4 is a thing.

**Comment by Avamander** [comment]
Honestly, if any login attempts are logged then things like fail2ban and OSSEC can handle the task themselves, better keep the MTA simple and not have two things to debug or to set up.

**Comment by foxcpp** [comment]
Added fail2ban config to the wiki (https://github.com/foxcpp/maddy/wiki/fail2ban-configuration).
