### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by foxcpp** [foxcpp/maddy#90]
Meta-issue for tracking state of tests coverage.

**Goal:** 70% total source code coverage

- [ ] internal/address (65.6% at da9bf2244)
- [x] internal/auth (100.0% at da9bf2244)
- [ ] internal/auth/external 
- [ ] internal/auth/pam 
- [ ] internal/auth/shadow 
- [ ] internal/buffer 
- [ ] internal/check 
- [ ] internal/check/command 
- [ ] internal/check/dkim 
- [x] internal/check/dns (82.3% at da9bf2244)
- [ ] internal/check/dnsbl (44.9% at da9bf2244)
- [ ] internal/check/requiretls 
- [ ] internal/check/spf 
- [ ] internal/config (32.4% at da9bf2244)
- [x] internal/config/lexer (88.5% at da9bf2244)
- [ ] internal/config/module 
- [x] internal/dmarc (91.1% at da9bf2244)
- [ ] internal/dns 
- [ ] internal/dsn 
- [ ] internal/endpoint/imap 
- [x] internal/endpoint/smtp (71.8% at da9bf2244)
- [ ] internal/exterrors 
- [x] internal/future (83.3% at da9bf2244)
- [ ] internal/hooks 
- [ ] internal/limits 
- [ ] internal/limits/limiters 
- [ ] internal/log 
- [ ] internal/modify (66.2% at da9bf2244)
- [x] internal/modify/dkim (71.7% at da9bf2244)
- [ ] internal/module 
- [x] internal/msgpipeline (73.5% at da9bf2244)
- [ ] internal/smtpconn (46.1% at da9bf2244)
- [ ] internal/storage/sql (0.5% at da9bf2244)
- [ ] internal/target 
- [x] internal/target/queue (75.3% at da9bf2244)
- [ ] internal/target/remote (64.0% at da9bf2244)
- [x] internal/target/smtp_downstream (80.2% at da9bf2244)
- [ ] internal/updatepipe 
- [x] pkg/cfgparser (91.7% at da9bf2244)
- [x] pkg/logparser (87.5% at da9bf2244)

Related: #168

**Comment by foxcpp** [comment]
One trouble with automatic testing for maddy code is that a significant portion of code is working with DNS (how one could test that 'remote' module implmenetation is behaving correctly?). Perhaps it is worth having an ability to replace resolver? This will also work for built-in DNSSEC support mentioned in #50.

Integration with libraries making connections is possible by implementing the net.Dialer interface. But here is a problem with libraries that interact with DNS (go-msgauth/dkim?).

**Comment by emersion** [comment]
Having a [resolver](https://golang.org/pkg/net/#Resolver) interface is probably a good idea.

**Comment by foxcpp** [comment]
I guess something like that is going to work well for us:
```go
type Resolver interface {
  LookupAddr(ctx context.Context, addr string) (names []string, err error)
  LookupHost(ctx context.Context, host string) (addrs []string, err error)
  LookupMX(ctx context.Context, name string) ([]*net.MX, error)
  LookupTXT(ctx context.Context, name string) ([]string, error)
}
```
I'm adding context here, so net.DefaultResolver will implement it.

Then add the implementer of the Dialer interface that uses that interface. It will be passed to libraries that need to make connections.

Then add subsets of that interface to libraries that need to use DNS. Perhaps, versions of functions accepting Resolver argument.

We can then probably even wire things up to maddys module system. But I'm not sure about how to make it look good and simple.

**Comment by foxcpp** [comment]
Depends on #95.

**Comment by foxcpp** [comment]
Closing as no-longer-relevant meta issue. Tests are to be added to components as we go.
