### ISSUE TITLE
Enforce SPF policy

### ISSUE THREAD

**Issue by foxcpp** [foxcpp/maddy#91]
Required for #39. This will also make currently present check_source_* obsolete.

**Comment by emersion** [comment]
SPF is pretty dumb. It breaks mailing lists. I'd say -1 to supporting it.

**Comment by foxcpp** [comment]
So what should be used instead of it?

**Comment by emersion** [comment]
DKIM

**Comment by foxcpp** [comment]
Alright. No SPF then.

**Comment by jlelse** [comment]
> SPF is pretty dumb. It breaks mailing lists. I'd say -1 to supporting it.

I just want to understand the reason behind that. Why does SPF break mailing lists?

> Required for #39.

Doesn't DMARC require both SPF and DKIM?

**Comment by emersion** [comment]
>Why does SPF break mailing lists?

SPF allows domain names to specify authorized outgoing servers. It means that if `bleh@example.org` has configured SPF, only `example.org` can send emails with that `MAIL FROM`. This sounds fine, but the annoying mistake comes from DMARC alignment checks that require `MAIL FROM` to be the same as the `From` header field. For this reason, SPF alignment is broken on mailing lists, where the `MAIL FROM` is the list's and the `From` is the original author.

**Comment by foxcpp** [comment]
>Doesn't DMARC require both SPF and DKIM?

I think we will pretend that SPF policy check always passes.

**Comment by emersion** [comment]
>     I think we will pretend that SPF policy check always passes while checking DMRAC.

No, instead there is a "none" status

**Comment by foxcpp** [comment]
I was wrong in dd9f4da68401df42d1607b8b0148d7acd795ae46. DMARC RFC seems to require SPF support in "proper" DMARC implementation:
https://tools.ietf.org/html/rfc7489#section-6.6.2
> To arrive at a policy for an individual message, Mail Receivers MUST
   perform the following actions or their semantic equivalents.

>4. Perform SPF validation checks.  The results of this step are
       passed to the remainder of the algorithm and MUST include the
       domain name used to complete the SPF check.

So I guess we will have to support SPF in one way or another, reopening.

**Comment by foxcpp** [comment]
Library to use: https://github.com/albertito/spf (https://godoc.org/blitiri.com.ar/go/spf).
