### ISSUE TITLE
Web page with documentation

### ISSUE THREAD

**Issue by foxcpp** [foxcpp/maddy#92]
Viewing the raw scd file on GitHub is an unpleasant experience. Publishing an HTML-rendered version of the man page somewhere will make it better. 

It was briefly discussed in #47 but left unaddressed.
Adding to the 0.1 milestone since we definitely want user-friendly documentation before the release.

**Comment by emersion** [comment]
Related: http://piumarta.com/software/tty2html/

**Comment by foxcpp** [comment]
Reopening, scdoc sources need quite a lot of post-processing to make them usable as Markdown documents. It might be worth hacking scdoc to provide HTML.

**Comment by foxcpp** [comment]
https://foxcpp.dev/maddy-reference
